#!/usr/bin/env python3
"""Concatenates the migrations into one file for the Supabase SQL editor.

The four numbered files are the source of truth. This exists only so setting a
project up is one paste instead of four, and so a re-run after a failure is one
action instead of remembering which of them already applied.

    python3 tool/build_migration.py
"""

from pathlib import Path

PARTS = [
    "0001_schema.sql",
    "0002_policies.sql",
    "0003_rpc.sql",
    "0004_accounts.sql",
    "0005_photos.sql",
    "0006_plans.sql",
    "0007_hardening.sql",
]

HEADER = """\
-- ============================================================================
--  EZ Order — complete setup, in one paste
-- ============================================================================
--
--  Generated by concatenating the numbered files in this directory, in order,
--  for the Supabase SQL editor. They are the source of truth; this is only
--  convenience.
--
--  Safe to run more than once: every table is `create table if not exists`,
--  every function `create or replace`, every policy dropped before it is
--  created. If a run fails part way, fix the cause and run the whole thing
--  again.
--
--  Regenerate with:  python3 tool/build_migration.py
-- ============================================================================

"""


def main() -> None:
    root = Path(__file__).resolve().parent.parent / "supabase" / "migrations"
    chunks = [HEADER]
    for name in PARTS:
        body = (root / name).read_text()
        chunks.append(
            f"\n-- >>>>>>>>>>>>>>>>>>>>>>  {name}  <<<<<<<<<<<<<<<<<<<<<<\n\n{body}"
        )
    target = root / "all_in_one.sql"
    target.write_text("".join(chunks))
    print(f"wrote {target.relative_to(root.parent.parent)} "
          f"({len(''.join(chunks).splitlines())} lines)")


if __name__ == "__main__":
    main()
