-- ============================================================================
--  EZ Order — complete setup, in one paste
-- ============================================================================
--
--  Generated by concatenating the four files in this directory, in order, for
--  the Supabase SQL editor. They are the source of truth; this is convenience.
--
--  Safe to run more than once: every table is `create table if not exists`,
--  every function `create or replace`, every policy dropped before it is
--  created. If a run fails part way, fix the cause and run the whole thing
--  again.
--
--  Regenerate with:  python3 tool/build_migration.py
-- ============================================================================


-- >>>>>>>>>>>>>>>>>>>>>>  0001_schema.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — schema
-- ============================================================================
--
--  Multi-tenant: one Supabase project serves many restaurants, and every row
--  that belongs to a restaurant carries `restaurant_id`. Which restaurant a
--  member of staff belongs to is decided by their row in `staff`, never by
--  anything the client sends, so a tampered client cannot reach across into
--  someone else's orders.
--
--  Run order: 0001_schema.sql, then 0002_policies.sql, then 0003_rpc.sql.
--  0004_seed.sql is optional and creates a demo restaurant to look at.
--
--  Menus are readable by anyone: a diner scans a QR code and has to be able to
--  read the menu before they are anyone at all. Orders are not — see
--  0002_policies.sql.
-- ============================================================================

-- Supabase ships pgcrypto in the `extensions` schema and this is normally a
-- no-op. It is spelled out so a bare Postgres puts crypt() and gen_salt()
-- where the account functions in 0004 expect to find them.
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------- restaurants

create table if not exists public.restaurants (
  id                uuid primary key default gen_random_uuid(),
  -- Appears in the QR link, so it has to be URL-safe and stable.
  slug              text not null unique
                      check (slug ~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$'),
  name              text not null check (length(trim(name)) > 0),
  name_km           text not null default '',
  logo              text not null default '🍽️',
  phone             text not null default '',
  address           text not null default '',
  currency_symbol   text not null default '$',
  currency_code     text not null default 'USD',
  -- Rule 10: what the cashier may accept. First entry is the default.
  payment_methods   text[] not null default array['Cash','KHQR','Card','Other'],
  -- Rule 12: order numbers are unique per restaurant. Handed out by
  -- next_order_number() under a row lock, never by the client.
  next_order_number integer not null default 101,
  created_at        timestamptz not null default now()
);

comment on column public.restaurants.next_order_number is
  'Next order number to hand out. Incremented under a row lock by '
  'next_order_number(); never written by a client.';

-- --------------------------------------------------------------------- staff

-- One row per person who can sign in. The primary key IS the auth user id, so
-- `auth.uid()` is enough to find someone's restaurant and role in one lookup.
create table if not exists public.staff (
  id            uuid primary key references auth.users(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name          text not null check (length(trim(name)) > 0),
  role          text not null check (role in ('ADMIN','KITCHEN','CASHIER')),
  -- Admins sign in by username; kitchen and cashier tap their name and enter a
  -- PIN, so they have none. Unique per restaurant, not globally: two
  -- restaurants may each have an "admin".
  username      text not null default '',
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);

create unique index if not exists staff_username_per_restaurant
  on public.staff (restaurant_id, lower(username))
  where username <> '';

create index if not exists staff_restaurant_idx on public.staff (restaurant_id);

-- ---------------------------------------------------------------- categories

create table if not exists public.categories (
  id            uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name          text not null check (length(trim(name)) > 0),
  name_km       text not null default '',
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists categories_restaurant_idx
  on public.categories (restaurant_id, sort_order);

-- ---------------------------------------------------------------- menu items

create table if not exists public.menu_items (
  id               uuid primary key default gen_random_uuid(),
  restaurant_id    uuid not null references public.restaurants(id) on delete cascade,
  -- Deleting a category takes its dishes with it, matching the admin UI, which
  -- warns how many dishes will go.
  category_id      uuid not null references public.categories(id) on delete cascade,
  name             text not null check (length(trim(name)) > 0),
  name_km          text not null default '',
  description      text not null default '',
  description_km   text not null default '',
  price            numeric(10,2) not null check (price >= 0),
  discount_percent integer not null default 0
                     check (discount_percent between 0 and 90),
  image            text not null default 'plate',
  -- Base64 of a photo the admin uploaded, capped in the client at ~700KB.
  photo            text,
  available        boolean not null default true,
  popular          boolean not null default false,
  signature        boolean not null default false,
  created_at       timestamptz not null default now()
);

create index if not exists menu_items_restaurant_idx
  on public.menu_items (restaurant_id);
create index if not exists menu_items_category_idx
  on public.menu_items (category_id);

-- --------------------------------------------------------------------- tables

create table if not exists public.restaurant_tables (
  id            uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  number        text not null check (length(trim(number)) > 0),
  name          text not null default '',
  -- Rule 2: what the printed QR code encodes. Unique across the project so a
  -- scan resolves to exactly one table without knowing the restaurant first.
  qr_id         text not null unique,
  created_at    timestamptz not null default now(),
  unique (restaurant_id, number)
);

create index if not exists tables_restaurant_idx
  on public.restaurant_tables (restaurant_id);

-- --------------------------------------------------------------------- orders

create table if not exists public.orders (
  id             uuid primary key default gen_random_uuid(),
  restaurant_id  uuid not null references public.restaurants(id) on delete cascade,
  order_number   integer not null,
  type           text not null default 'DINE_IN'
                   check (type in ('DINE_IN','TAKEAWAY')),
  -- Rule 11 as amended: a dine-in order carries its table, a takeaway order
  -- carries none and is called by its number.
  table_id       uuid references public.restaurant_tables(id) on delete set null,
  -- Snapshot, so a renamed or deleted table does not rewrite history.
  table_number   text,
  status         text not null default 'NEW'
                   check (status in
                     ('NEW','COOKING','READY','PAID','COMPLETED','CANCELLED')),
  subtotal       numeric(10,2) not null default 0 check (subtotal >= 0),
  total          numeric(10,2) not null default 0 check (total >= 0),
  customer_note  text,
  payment_method text,
  -- Name of the staff member who keyed it in at the counter; null when the
  -- customer placed it from their own phone.
  placed_by      text,
  cancelled_by   text,
  -- The anonymous auth user who placed it, so RLS can scope "my orders"
  -- without a diner needing an account.
  customer_id    uuid,
  created_at     timestamptz not null default now(),
  paid_at        timestamptz,
  cancelled_at   timestamptz,
  unique (restaurant_id, order_number),
  -- Rule 11, enforced by the database rather than only by the client.
  constraint dine_in_needs_a_table
    check (type <> 'DINE_IN' or table_number is not null)
);

create index if not exists orders_restaurant_status_idx
  on public.orders (restaurant_id, status, created_at);
create index if not exists orders_customer_idx
  on public.orders (customer_id) where customer_id is not null;

-- ---------------------------------------------------------------- order items

create table if not exists public.order_items (
  id       uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  -- Not a foreign key on purpose: a dish removed from the menu next week must
  -- not erase what somebody ate today. Name and price are snapshots too.
  food_id  uuid,
  name     text not null,
  name_km  text not null default '',
  price    numeric(10,2) not null check (price >= 0),
  quantity integer not null check (quantity > 0),
  note     text
);

create index if not exists order_items_order_idx on public.order_items (order_id);

-- ------------------------------------------------------------------ realtime

-- What the kitchen board, the till and the customer's tracker listen to. This
-- is what makes the live sync real across devices rather than a trick that
-- only worked because everything was on one phone.
alter table public.orders replica identity full;
alter table public.order_items replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'order_items'
  ) then
    alter publication supabase_realtime add table public.order_items;
  end if;
end $$;

-- >>>>>>>>>>>>>>>>>>>>>>  0002_policies.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — row level security
-- ============================================================================
--
--  The shape of it:
--
--    * Menus, tables and restaurant profiles are world-readable. A diner scans
--      a sticker and must be able to read the menu before they are anyone.
--    * Orders are readable by the staff of that restaurant, and by the diner
--      who placed them. Nobody else.
--    * Nothing is written directly. Every mutation goes through a SECURITY
--      DEFINER function in 0003_rpc.sql that checks the caller's role and the
--      order's state first. That is why you will find no INSERT or UPDATE
--      policy on `orders` below — the absence is deliberate, not an oversight.
--
--  Doing it this way means the state machine (Rule 6, Rule 7, cancel-only-
--  while-queued) is enforced in one place in the database, instead of being
--  reconstructed out of CHECK constraints and per-column policies.
-- ============================================================================

alter table public.restaurants       enable row level security;
alter table public.staff             enable row level security;
alter table public.categories        enable row level security;
alter table public.menu_items        enable row level security;
alter table public.restaurant_tables enable row level security;
alter table public.orders            enable row level security;
alter table public.order_items       enable row level security;

-- ----------------------------------------------------------------- helpers

-- Which restaurant the caller works for, or null if they are a diner.
--
-- SECURITY DEFINER so it can read `staff` without tripping the policies on
-- `staff`, which would otherwise recurse: the policy needs the function and
-- the function needs the table. `search_path` is pinned so the function cannot
-- be redirected at a shadowed table.
create or replace function public.current_restaurant_id()
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select restaurant_id from public.staff
  where id = auth.uid() and active
$$;

create or replace function public.current_staff_role()
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select role from public.staff
  where id = auth.uid() and active
$$;

-- Admin is a superset: in a small shop the owner works the kitchen and the
-- till as well. Mirrors StaffRole in lib/models/staff_account.dart.
--
-- Every one of these coalesces to false, and that is load-bearing. For a caller
-- who is not staff at all, current_staff_role() is NULL, and `NULL = 'ADMIN'`
-- is NULL rather than false. The guards read `if not can_manage_restaurant()
-- then raise`, and `if NULL then` does not take the branch — so without the
-- coalesce an anonymous caller walks straight past the permission check and is
-- stopped only by whatever constraint happens to catch them further down.
create or replace function public.can_manage_restaurant()
returns boolean language sql stable
set search_path = public, pg_temp
as $$ select coalesce(public.current_staff_role() = 'ADMIN', false) $$;

create or replace function public.can_work_kitchen()
returns boolean language sql stable
set search_path = public, pg_temp
as $$ select coalesce(public.current_staff_role() in ('ADMIN','KITCHEN'), false) $$;

create or replace function public.can_take_payment()
returns boolean language sql stable
set search_path = public, pg_temp
as $$ select coalesce(public.current_staff_role() in ('ADMIN','CASHIER'), false) $$;

grant execute on function public.current_restaurant_id() to anon, authenticated;
grant execute on function public.current_staff_role()   to anon, authenticated;
grant execute on function public.can_manage_restaurant() to anon, authenticated;
grant execute on function public.can_work_kitchen()      to anon, authenticated;
grant execute on function public.can_take_payment()      to anon, authenticated;

-- ------------------------------------------------------------- restaurants

-- Public: a diner needs the name, logo, currency and payment methods to read
-- a menu and a receipt. None of that is a secret.
drop policy if exists restaurants_read on public.restaurants;
create policy restaurants_read on public.restaurants
  for select using (true);

-- Only an admin, and only their own restaurant. `next_order_number` is
-- protected separately by a trigger below.
drop policy if exists restaurants_admin_update on public.restaurants;
create policy restaurants_admin_update on public.restaurants
  for update
  using  (id = public.current_restaurant_id() and public.can_manage_restaurant())
  with check (id = public.current_restaurant_id() and public.can_manage_restaurant());

-- An admin editing settings must not be able to rewind the order counter and
-- collide with numbers already issued.
create or replace function public.protect_order_counter()
returns trigger language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.next_order_number <> old.next_order_number then
    new.next_order_number := old.next_order_number;
  end if;
  if new.slug <> old.slug then
    raise exception 'A restaurant slug cannot be changed once QR codes are printed';
  end if;
  return new;
end $$;

drop trigger if exists restaurants_protect_counter on public.restaurants;
create trigger restaurants_protect_counter
  before update on public.restaurants
  for each row execute function public.protect_order_counter();

-- ------------------------------------------------------------------- staff

-- Staff may see their colleagues; the PIN pad lists kitchen and cashier names
-- to tap. No secrets live here — passwords are Supabase Auth's problem.
drop policy if exists staff_read on public.staff;
create policy staff_read on public.staff
  for select using (restaurant_id = public.current_restaurant_id());

-- Creating and deleting staff also creates and deletes auth users, so it runs
-- through RPCs rather than direct writes. Admins may rename and deactivate.
drop policy if exists staff_admin_update on public.staff;
create policy staff_admin_update on public.staff
  for update
  using  (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant())
  with check (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant()
          -- Moving someone to another restaurant, or promoting them to admin
          -- by hand, is not an edit — it is a different account.
          and role = (select role from public.staff s where s.id = staff.id));

-- --------------------------------------------------- menu, categories, tables

-- Public read: this is the menu a diner scans for.
drop policy if exists categories_read on public.categories;
create policy categories_read on public.categories for select using (true);

drop policy if exists menu_items_read on public.menu_items;
create policy menu_items_read on public.menu_items for select using (true);

drop policy if exists tables_read on public.restaurant_tables;
create policy tables_read on public.restaurant_tables for select using (true);

-- Admin-only writes, scoped to their own restaurant. `with check` on insert
-- and update is what stops a client planting a row in another restaurant.
drop policy if exists categories_admin_write on public.categories;
create policy categories_admin_write on public.categories
  for all
  using  (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant())
  with check (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant());

drop policy if exists menu_items_admin_write on public.menu_items;
create policy menu_items_admin_write on public.menu_items
  for all
  using  (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant())
  with check (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant());

drop policy if exists tables_admin_write on public.restaurant_tables;
create policy tables_admin_write on public.restaurant_tables
  for all
  using  (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant())
  with check (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant());

-- ------------------------------------------------------------------ orders

-- Staff see every order in their own restaurant. A diner sees the orders they
-- placed, and nothing else — not the table's, not the restaurant's.
--
-- Deliberately no INSERT, UPDATE or DELETE policy: every write goes through
-- the functions in 0003_rpc.sql, which check role and state first.
drop policy if exists orders_read on public.orders;
create policy orders_read on public.orders
  for select using (
    restaurant_id = public.current_restaurant_id()
    or (customer_id is not null and customer_id = auth.uid())
  );

drop policy if exists order_items_read on public.order_items;
create policy order_items_read on public.order_items
  for select using (
    exists (
      select 1 from public.orders o
      where o.id = order_items.order_id
        and (
          o.restaurant_id = public.current_restaurant_id()
          or (o.customer_id is not null and o.customer_id = auth.uid())
        )
    )
  );

-- >>>>>>>>>>>>>>>>>>>>>>  0003_rpc.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — the mutations
-- ============================================================================
--
--  Every write to an order goes through one of these. They are SECURITY
--  DEFINER, so they can write tables that have no INSERT/UPDATE policy at all,
--  and each one checks the caller's role and the order's current state before
--  it does. That puts the rules the app is built on in exactly one place:
--
--    Rule 6   kitchen owns NEW -> COOKING -> READY
--    Rule 7   cashier owns READY -> PAID -> COMPLETED
--    Rule 12  order numbers are unique per restaurant
--             an order may only be edited or cancelled while still queued
--
--  The client mirrors these checks so it can grey out a button, but the client
--  is not what enforces them.
-- ============================================================================

-- ------------------------------------------------------------ order numbers

-- Rule 12. The UPDATE takes a row lock, so two tills submitting at the same
-- instant get different numbers rather than a duplicate-key error.
create or replace function public.next_order_number(p_restaurant_id uuid)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_number integer;
begin
  update public.restaurants
     set next_order_number = next_order_number + 1
   where id = p_restaurant_id
   returning next_order_number - 1 into v_number;

  if v_number is null then
    raise exception 'Unknown restaurant';
  end if;
  return v_number;
end $$;

revoke execute on function public.next_order_number(uuid) from anon, authenticated;

-- ------------------------------------------------------------- place_order

-- Used by a diner on their own phone and by a cashier at the counter. The
-- difference is p_placed_by: null when the customer placed it themselves.
--
-- p_items is a JSON array of {food_id, name, name_km, price, quantity, note}.
-- Prices are taken from the menu here, not from the client, so a tampered
-- client cannot order a $12 dish for 1 cent.
create or replace function public.place_order(
  p_restaurant_id uuid,
  p_type          text,
  p_table_id      uuid,
  p_note          text,
  p_items         jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order_id     uuid;
  v_number       integer;
  v_table_number text;
  v_subtotal     numeric(10,2) := 0;
  v_placed_by    text;
  v_item         jsonb;
  v_price        numeric(10,2);
  v_available    boolean;
  v_name         text;
  v_name_km      text;
  v_quantity     integer;
begin
  if p_type not in ('DINE_IN','TAKEAWAY') then
    raise exception 'An order is either DINE_IN or TAKEAWAY';
  end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'The cart is empty';
  end if;

  -- Rule 11: a dine-in order carries its table; takeaway carries none.
  if p_type = 'DINE_IN' then
    select number into v_table_number
      from public.restaurant_tables
     where id = p_table_id and restaurant_id = p_restaurant_id;
    if v_table_number is null then
      raise exception 'No table selected — scan a table QR first';
    end if;
  else
    p_table_id := null;
  end if;

  -- A member of staff placing this is taking it at the counter. Anyone else
  -- is the customer, and their order is tagged with their anonymous uid so
  -- they can watch it without an account.
  if public.current_restaurant_id() = p_restaurant_id then
    if not public.can_take_payment() then
      raise exception 'You are not allowed to take an order for a customer';
    end if;
    select name into v_placed_by from public.staff where id = auth.uid();
  end if;

  v_number := public.next_order_number(p_restaurant_id);

  insert into public.orders (
    restaurant_id, order_number, type, table_id, table_number,
    status, customer_note, placed_by, customer_id
  ) values (
    p_restaurant_id, v_number, p_type, p_table_id, v_table_number,
    'NEW', nullif(trim(coalesce(p_note,'')), ''), v_placed_by,
    case when v_placed_by is null then auth.uid() end
  )
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_quantity := greatest(1, coalesce((v_item->>'quantity')::integer, 1));

    -- Rule 9, and the price, both read from the menu rather than trusted.
    select
        case when discount_percent > 0
             then round(price * (100 - discount_percent) / 100.0, 2)
             else price end,
        available, name, name_km
      into v_price, v_available, v_name, v_name_km
      from public.menu_items
     where id = (v_item->>'food_id')::uuid
       and restaurant_id = p_restaurant_id;

    if v_price is null then
      raise exception 'That dish is not on this menu';
    end if;
    if not v_available then
      raise exception '% is sold out', v_name;
    end if;

    insert into public.order_items
      (order_id, food_id, name, name_km, price, quantity, note)
    values
      (v_order_id, (v_item->>'food_id')::uuid, v_name, v_name_km,
       v_price, v_quantity, nullif(trim(coalesce(v_item->>'note','')), ''));

    v_subtotal := v_subtotal + v_price * v_quantity;
  end loop;

  update public.orders
     set subtotal = v_subtotal, total = v_subtotal
   where id = v_order_id;

  return v_order_id;
end $$;

grant execute on function
  public.place_order(uuid, text, uuid, text, jsonb) to anon, authenticated;

-- ------------------------------------------------------- status transitions

-- Shared by all four transitions: find the order, check it belongs to the
-- caller's restaurant, and check it is where it is expected to be.
create or replace function public.assert_transition(
  p_order_id uuid,
  p_from     text
)
returns public.orders
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
begin
  select * into v_order from public.orders where id = p_order_id;
  if v_order.id is null then
    raise exception 'Unknown order';
  end if;
  if v_order.restaurant_id is distinct from public.current_restaurant_id() then
    raise exception 'That order belongs to another restaurant';
  end if;
  if v_order.status <> p_from then
    raise exception 'Order #% is %, it cannot move from %',
      v_order.order_number, v_order.status, p_from;
  end if;
  return v_order;
end $$;

revoke execute on function public.assert_transition(uuid, text) from anon, authenticated;

-- Rule 6 — kitchen owns NEW -> COOKING -> READY.
create or replace function public.start_cooking(p_order_id uuid)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can_work_kitchen() then
    raise exception 'You are not allowed to work the kitchen';
  end if;
  perform public.assert_transition(p_order_id, 'NEW');
  update public.orders set status = 'COOKING' where id = p_order_id;
end $$;

create or replace function public.mark_ready(p_order_id uuid)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can_work_kitchen() then
    raise exception 'You are not allowed to work the kitchen';
  end if;
  perform public.assert_transition(p_order_id, 'COOKING');
  update public.orders set status = 'READY' where id = p_order_id;
end $$;

-- Rule 7 — cashier owns READY -> PAID -> COMPLETED.
create or replace function public.collect_payment(
  p_order_id uuid,
  p_method   text
)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
begin
  if not public.can_take_payment() then
    raise exception 'You are not allowed to take payment';
  end if;
  v_order := public.assert_transition(p_order_id, 'READY');

  -- Rule 10: only a method this restaurant actually accepts.
  if not exists (
    select 1 from public.restaurants
     where id = v_order.restaurant_id and p_method = any(payment_methods)
  ) then
    raise exception '% is not a payment method this restaurant accepts', p_method;
  end if;

  update public.orders
     set status = 'PAID', payment_method = p_method, paid_at = now()
   where id = p_order_id;
end $$;

create or replace function public.complete_order(p_order_id uuid)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can_take_payment() then
    raise exception 'You are not allowed to close an order';
  end if;
  perform public.assert_transition(p_order_id, 'PAID');
  update public.orders set status = 'COMPLETED' where id = p_order_id;
end $$;

-- Only while it is still queued: once a pan is on the heat the dish exists
-- whether or not it is still wanted.
create or replace function public.cancel_order(p_order_id uuid)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
  v_name  text;
begin
  if not public.can_take_payment() then
    raise exception 'You are not allowed to cancel an order';
  end if;
  v_order := public.assert_transition(p_order_id, 'NEW');
  select name into v_name from public.staff where id = auth.uid();

  update public.orders
     set status = 'CANCELLED', cancelled_by = v_name, cancelled_at = now()
   where id = p_order_id;
end $$;

grant execute on function public.start_cooking(uuid)          to authenticated;
grant execute on function public.mark_ready(uuid)             to authenticated;
grant execute on function public.collect_payment(uuid, text)  to authenticated;
grant execute on function public.complete_order(uuid)         to authenticated;
grant execute on function public.cancel_order(uuid)           to authenticated;

-- --------------------------------------------------------- editing an order

-- A quantity of zero drops the line. Removing the last one is refused: an
-- order with nothing on it is not something the kitchen or the till can act
-- on, so that case is a cancellation and has to be made as one.
create or replace function public.set_order_item_quantity(
  p_order_id uuid,
  p_item_id  uuid,
  p_quantity integer
)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
  v_count integer;
begin
  if not public.can_take_payment() then
    raise exception 'You are not allowed to change an order';
  end if;
  v_order := public.assert_transition(p_order_id, 'NEW');

  if not exists (
    select 1 from public.order_items
     where id = p_item_id and order_id = p_order_id
  ) then
    raise exception 'That dish is not on this order';
  end if;

  select count(*) into v_count from public.order_items where order_id = p_order_id;

  if p_quantity <= 0 then
    if v_count <= 1 then
      raise exception
        'That is the only dish left — cancel order #% instead',
        v_order.order_number;
    end if;
    delete from public.order_items where id = p_item_id;
  else
    update public.order_items set quantity = p_quantity where id = p_item_id;
  end if;

  update public.orders o
     set subtotal = c.sum, total = c.sum
    from (
      select coalesce(sum(price * quantity), 0)::numeric(10,2) as sum
        from public.order_items where order_id = p_order_id
    ) c
   where o.id = p_order_id;
end $$;

grant execute on function
  public.set_order_item_quantity(uuid, uuid, integer) to authenticated;

-- --------------------------------------------------------- staff directory

-- The PIN pad lists kitchen and cashier names to tap, and it has to do that
-- before anyone is signed in — so this one is deliberately public.
--
-- It exposes staff first names and role for a restaurant whose slug you
-- already know. It exposes no contact details and no secrets; passwords are
-- Supabase Auth's problem and are never in this table. If even the names are
-- too much for your setting, drop the grant to `anon` and have staff sign in
-- by typing their username instead.
create or replace function public.staff_directory(p_slug text)
returns table (id uuid, name text, role text)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select s.id, s.name, s.role
    from public.staff s
    join public.restaurants r on r.id = s.restaurant_id
   where r.slug = p_slug
     and s.active
     and s.role <> 'ADMIN'
   order by s.name
$$;

grant execute on function public.staff_directory(text) to anon, authenticated;

-- >>>>>>>>>>>>>>>>>>>>>>  0004_accounts.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — staff accounts
-- ============================================================================
--
--  Staff are real Supabase Auth users, so row level security can trust
--  `auth.uid()`. They never type an email address, though: the app derives one
--  from what they do type.
--
--      admin            <username>@<slug>.staff.ezorder.app
--      kitchen/cashier  <staff-id>@<slug>.staff.ezorder.app
--
--  Both are derivable by the client with no lookup — the admin's from the
--  username they type, everyone else's from the id in staff_directory(). That
--  matters: it means there is no "does this username exist" endpoint to probe.
--
--  Creating an auth user normally needs the service_role key, which must never
--  be in a phone app. These functions are SECURITY DEFINER instead, so an
--  admin signed in with the anon key can create staff for their own restaurant
--  and nobody else's.
-- ============================================================================

-- Derives the login address. Kept in SQL as well as Dart so both agree.
create or replace function public.staff_login_email(
  p_slug  text,
  p_local text
)
returns text language sql immutable
set search_path = public, pg_temp
as $$ select lower(p_local) || '@' || lower(p_slug) || '.staff.ezorder.app' $$;

grant execute on function public.staff_login_email(text, text) to anon, authenticated;

-- ---------------------------------------------------- creating an auth user
--
-- Writes the two rows GoTrue expects: the user, and an `email` identity. The
-- identities table has gained columns across GoTrue versions, so the insert is
-- built dynamically from what actually exists in this project rather than
-- assuming one particular version.
create or replace function public.create_auth_user(
  p_email    text,
  p_password text
)
returns uuid
language plpgsql
security definer
-- `extensions` is on the path because that is where Supabase installs
-- pgcrypto: crypt() and gen_salt() are not in `public` and will not be found
-- without it.
set search_path = public, extensions, auth, pg_temp
as $$
declare
  v_id  uuid := gen_random_uuid();
  v_cols text := 'user_id, identity_data, provider, last_sign_in_at, created_at, updated_at';
  v_vals text := '$1, $2, ''email'', now(), now(), now()';
begin
  if p_password is null or length(p_password) < 6 then
    raise exception 'A password or PIN must be at least 6 characters';
  end if;
  if exists (select 1 from auth.users where lower(email) = lower(p_email)) then
    raise exception 'Another account already uses that username';
  end if;

  insert into auth.users (
    instance_id, id, aud, role, email, encrypted_password,
    email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
    created_at, updated_at,
    confirmation_token, recovery_token, email_change_token_new, email_change
  ) values (
    '00000000-0000-0000-0000-000000000000', v_id, 'authenticated',
    'authenticated', lower(p_email), crypt(p_password, gen_salt('bf')),
    now(), '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb,
    now(), now(), '', '', '', ''
  );

  -- `id` and `provider_id` appeared in later GoTrue versions.
  if exists (select 1 from information_schema.columns
              where table_schema = 'auth' and table_name = 'identities'
                and column_name = 'id') then
    v_cols := 'id, ' || v_cols;
    v_vals := 'gen_random_uuid(), ' || v_vals;
  end if;
  if exists (select 1 from information_schema.columns
              where table_schema = 'auth' and table_name = 'identities'
                and column_name = 'provider_id') then
    v_cols := v_cols || ', provider_id';
    v_vals := v_vals || ', $1::text';
  end if;

  execute format('insert into auth.identities (%s) values (%s)', v_cols, v_vals)
    using v_id, jsonb_build_object('sub', v_id::text, 'email', lower(p_email));

  return v_id;
end $$;

-- Never callable from a client; only from the functions below.
revoke execute on function public.create_auth_user(text, text) from anon, authenticated;

-- ------------------------------------------------------ bootstrap: run once
--
-- Creates a restaurant and its first admin. This is the only function you call
-- by hand, from the SQL editor, because until it has run there is no admin to
-- authorise anything.
--
--   select public.provision_restaurant('demo', 'ABC Restaurant',
--                                      'admin', 'a-long-password');
create or replace function public.provision_restaurant(
  p_slug           text,
  p_name           text,
  p_admin_username text,
  p_admin_password text
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_restaurant_id uuid;
  v_user_id       uuid;
begin
  if length(coalesce(p_admin_password,'')) < 8 then
    raise exception 'Give the owner a password of at least 8 characters';
  end if;

  insert into public.restaurants (slug, name)
  values (lower(p_slug), p_name)
  returning id into v_restaurant_id;

  v_user_id := public.create_auth_user(
    public.staff_login_email(p_slug, p_admin_username), p_admin_password);

  insert into public.staff (id, restaurant_id, name, role, username)
  values (v_user_id, v_restaurant_id, p_name || ' Owner', 'ADMIN',
          lower(p_admin_username));

  return v_restaurant_id;
end $$;

revoke execute on function
  public.provision_restaurant(text, text, text, text) from anon, authenticated;

-- ------------------------------------------------------------ manage staff

create or replace function public.create_staff_account(
  p_name     text,
  p_role     text,
  p_secret   text,
  p_username text default ''
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_restaurant_id uuid := public.current_restaurant_id();
  v_slug          text;
  v_user_id       uuid;
  v_local         text;
begin
  if not public.can_manage_restaurant() then
    raise exception 'You are not allowed to manage staff';
  end if;
  if p_role not in ('ADMIN','KITCHEN','CASHIER') then
    raise exception 'Unknown role %', p_role;
  end if;
  if p_role = 'ADMIN' and length(trim(coalesce(p_username,''))) = 0 then
    raise exception 'An admin needs a username';
  end if;

  select slug into v_slug from public.restaurants where id = v_restaurant_id;

  -- An admin's address comes from their username so they can sign in by
  -- typing it. Everyone else's comes from their id, which the PIN pad already
  -- has from staff_directory().
  if p_role = 'ADMIN' then
    v_local := lower(trim(p_username));
    v_user_id := public.create_auth_user(
      public.staff_login_email(v_slug, v_local), p_secret);
  else
    -- create_auth_user mints the id, so the address is built from a throwaway
    -- value and rewritten to the real id once we have it. The client derives
    -- the same address from staff_directory(), so the two always agree.
    v_user_id := public.create_auth_user(
      public.staff_login_email(v_slug, gen_random_uuid()::text), p_secret);
    update auth.users
       set email = public.staff_login_email(v_slug, v_user_id::text)
     where id = v_user_id;
    update auth.identities
       set identity_data = jsonb_build_object(
             'sub', v_user_id::text,
             'email', public.staff_login_email(v_slug, v_user_id::text))
     where user_id = v_user_id;
  end if;

  insert into public.staff (id, restaurant_id, name, role, username)
  values (v_user_id, v_restaurant_id, trim(p_name), p_role,
          case when p_role = 'ADMIN' then lower(trim(p_username)) else '' end);

  return v_user_id;
end $$;

grant execute on function
  public.create_staff_account(text, text, text, text) to authenticated;

create or replace function public.reset_staff_secret(
  p_staff_id uuid,
  p_secret   text
)
returns void language plpgsql security definer
-- See create_auth_user: pgcrypto lives in `extensions`.
set search_path = public, extensions, auth, pg_temp
as $$
begin
  if not public.can_manage_restaurant() then
    raise exception 'You are not allowed to manage staff';
  end if;
  if not exists (
    select 1 from public.staff
     where id = p_staff_id and restaurant_id = public.current_restaurant_id()
  ) then
    raise exception 'That account is not yours to change';
  end if;
  if length(coalesce(p_secret,'')) < 6 then
    raise exception 'A password or PIN must be at least 6 characters';
  end if;

  update auth.users
     set encrypted_password = crypt(p_secret, gen_salt('bf')), updated_at = now()
   where id = p_staff_id;
end $$;

grant execute on function public.reset_staff_secret(uuid, text) to authenticated;

-- Locking every admin out would be unrecoverable without the SQL editor, so
-- the last active one is protected — same guard the prototype had.
create or replace function public.assert_not_last_admin(p_staff_id uuid)
returns void language plpgsql
set search_path = public, pg_temp
as $$
begin
  if exists (select 1 from public.staff
              where id = p_staff_id and role = 'ADMIN' and active)
     and not exists (
       select 1 from public.staff
        where restaurant_id = public.current_restaurant_id()
          and role = 'ADMIN' and active and id <> p_staff_id
     )
  then
    raise exception 'There must be at least one active admin';
  end if;
end $$;

create or replace function public.set_staff_active(
  p_staff_id uuid,
  p_active   boolean
)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can_manage_restaurant() then
    raise exception 'You are not allowed to manage staff';
  end if;
  if not exists (
    select 1 from public.staff
     where id = p_staff_id and restaurant_id = public.current_restaurant_id()
  ) then
    raise exception 'That account is not yours to change';
  end if;
  if not p_active then
    perform public.assert_not_last_admin(p_staff_id);
  end if;

  update public.staff set active = p_active where id = p_staff_id;
end $$;

create or replace function public.delete_staff_account(p_staff_id uuid)
returns void language plpgsql security definer
set search_path = public, auth, pg_temp
as $$
begin
  if not public.can_manage_restaurant() then
    raise exception 'You are not allowed to manage staff';
  end if;
  if p_staff_id = auth.uid() then
    raise exception 'You cannot delete the account you are signed in with';
  end if;
  if not exists (
    select 1 from public.staff
     where id = p_staff_id and restaurant_id = public.current_restaurant_id()
  ) then
    raise exception 'That account is not yours to change';
  end if;
  perform public.assert_not_last_admin(p_staff_id);

  -- staff.id references auth.users on delete cascade, so this removes both.
  delete from auth.users where id = p_staff_id;
end $$;

grant execute on function public.set_staff_active(uuid, boolean) to authenticated;
grant execute on function public.delete_staff_account(uuid)      to authenticated;
