-- ============================================================================
--  EZ Order — complete setup, in one paste
-- ============================================================================
--
--  Generated by concatenating the numbered files in this directory, in order,
--  for the Supabase SQL editor. They are the source of truth; this is only
--  convenience.
--
--  Safe to run more than once: every table is `create table if not exists`,
--  every function `create or replace`, every policy dropped before it is
--  created. If a run fails part way, fix the cause and run the whole thing
--  again.
--
--  Regenerate with:  python3 tool/build_migration.py
-- ============================================================================


-- >>>>>>>>>>>>>>>>>>>>>>  0001_schema.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — schema
-- ============================================================================
--
--  Multi-tenant: one Supabase project serves many restaurants, and every row
--  that belongs to a restaurant carries `restaurant_id`. Which restaurant a
--  member of staff belongs to is decided by their row in `staff`, never by
--  anything the client sends, so a tampered client cannot reach across into
--  someone else's orders.
--
--  Run order: 0001_schema.sql, then 0002_policies.sql, then 0003_rpc.sql.
--  0004_seed.sql is optional and creates a demo restaurant to look at.
--
--  Menus are readable by anyone: a diner scans a QR code and has to be able to
--  read the menu before they are anyone at all. Orders are not — see
--  0002_policies.sql.
-- ============================================================================

-- Supabase ships pgcrypto in the `extensions` schema and this is normally a
-- no-op. It is spelled out so a bare Postgres puts crypt() and gen_salt()
-- where the account functions in 0004 expect to find them.
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------- restaurants

create table if not exists public.restaurants (
  id                uuid primary key default gen_random_uuid(),
  -- Appears in the QR link, so it has to be URL-safe and stable.
  slug              text not null unique
                      check (slug ~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$'),
  name              text not null check (length(trim(name)) > 0),
  name_km           text not null default '',
  logo              text not null default '🍽️',
  phone             text not null default '',
  address           text not null default '',
  currency_symbol   text not null default '$',
  currency_code     text not null default 'USD',
  -- Rule 10: what the cashier may accept. First entry is the default.
  payment_methods   text[] not null default array['Cash','KHQR','Card','Other'],
  -- Rule 12: order numbers are unique per restaurant. Handed out by
  -- next_order_number() under a row lock, never by the client.
  next_order_number integer not null default 101,
  created_at        timestamptz not null default now()
);

comment on column public.restaurants.next_order_number is
  'Next order number to hand out. Incremented under a row lock by '
  'next_order_number(); never written by a client.';

-- --------------------------------------------------------------------- staff

-- One row per person who can sign in. The primary key IS the auth user id, so
-- `auth.uid()` is enough to find someone's restaurant and role in one lookup.
create table if not exists public.staff (
  id            uuid primary key references auth.users(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name          text not null check (length(trim(name)) > 0),
  role          text not null check (role in ('ADMIN','KITCHEN','CASHIER')),
  -- Admins sign in by username; kitchen and cashier tap their name and enter a
  -- PIN, so they have none. Unique per restaurant, not globally: two
  -- restaurants may each have an "admin".
  username      text not null default '',
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);

create unique index if not exists staff_username_per_restaurant
  on public.staff (restaurant_id, lower(username))
  where username <> '';

create index if not exists staff_restaurant_idx on public.staff (restaurant_id);

-- ---------------------------------------------------------------- categories

create table if not exists public.categories (
  id            uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name          text not null check (length(trim(name)) > 0),
  name_km       text not null default '',
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists categories_restaurant_idx
  on public.categories (restaurant_id, sort_order);

-- ---------------------------------------------------------------- menu items

create table if not exists public.menu_items (
  id               uuid primary key default gen_random_uuid(),
  restaurant_id    uuid not null references public.restaurants(id) on delete cascade,
  -- Deleting a category takes its dishes with it, matching the admin UI, which
  -- warns how many dishes will go.
  category_id      uuid not null references public.categories(id) on delete cascade,
  name             text not null check (length(trim(name)) > 0),
  name_km          text not null default '',
  description      text not null default '',
  description_km   text not null default '',
  price            numeric(10,2) not null check (price >= 0),
  discount_percent integer not null default 0
                     check (discount_percent between 0 and 90),
  image            text not null default 'plate',
  -- Base64 of a photo the admin uploaded, capped in the client at ~700KB.
  photo            text,
  available        boolean not null default true,
  popular          boolean not null default false,
  signature        boolean not null default false,
  created_at       timestamptz not null default now()
);

create index if not exists menu_items_restaurant_idx
  on public.menu_items (restaurant_id);
create index if not exists menu_items_category_idx
  on public.menu_items (category_id);

-- --------------------------------------------------------------------- tables

create table if not exists public.restaurant_tables (
  id            uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  number        text not null check (length(trim(number)) > 0),
  name          text not null default '',
  -- Rule 2: what the printed QR code encodes. Unique across the project so a
  -- scan resolves to exactly one table without knowing the restaurant first.
  qr_id         text not null unique,
  created_at    timestamptz not null default now(),
  unique (restaurant_id, number)
);

create index if not exists tables_restaurant_idx
  on public.restaurant_tables (restaurant_id);

-- --------------------------------------------------------------------- orders

create table if not exists public.orders (
  id             uuid primary key default gen_random_uuid(),
  restaurant_id  uuid not null references public.restaurants(id) on delete cascade,
  order_number   integer not null,
  type           text not null default 'DINE_IN'
                   check (type in ('DINE_IN','TAKEAWAY')),
  -- Rule 11 as amended: a dine-in order carries its table, a takeaway order
  -- carries none and is called by its number.
  table_id       uuid references public.restaurant_tables(id) on delete set null,
  -- Snapshot, so a renamed or deleted table does not rewrite history.
  table_number   text,
  status         text not null default 'NEW'
                   check (status in
                     ('NEW','COOKING','READY','PAID','COMPLETED','CANCELLED')),
  subtotal       numeric(10,2) not null default 0 check (subtotal >= 0),
  total          numeric(10,2) not null default 0 check (total >= 0),
  customer_note  text,
  payment_method text,
  -- Name of the staff member who keyed it in at the counter; null when the
  -- customer placed it from their own phone.
  placed_by      text,
  cancelled_by   text,
  -- The anonymous auth user who placed it, so RLS can scope "my orders"
  -- without a diner needing an account.
  customer_id    uuid,
  created_at     timestamptz not null default now(),
  paid_at        timestamptz,
  cancelled_at   timestamptz,
  unique (restaurant_id, order_number),
  -- Rule 11, enforced by the database rather than only by the client.
  constraint dine_in_needs_a_table
    check (type <> 'DINE_IN' or table_number is not null)
);

create index if not exists orders_restaurant_status_idx
  on public.orders (restaurant_id, status, created_at);
create index if not exists orders_customer_idx
  on public.orders (customer_id) where customer_id is not null;

-- ---------------------------------------------------------------- order items

create table if not exists public.order_items (
  id       uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  -- Not a foreign key on purpose: a dish removed from the menu next week must
  -- not erase what somebody ate today. Name and price are snapshots too.
  food_id  uuid,
  name     text not null,
  name_km  text not null default '',
  price    numeric(10,2) not null check (price >= 0),
  quantity integer not null check (quantity > 0),
  note     text
);

create index if not exists order_items_order_idx on public.order_items (order_id);

-- ------------------------------------------------------------------ realtime

-- What the kitchen board, the till and the customer's tracker listen to. This
-- is what makes the live sync real across devices rather than a trick that
-- only worked because everything was on one phone.
alter table public.orders replica identity full;
alter table public.order_items replica identity full;

-- The menu is published too, so a dish the owner adds appears on a diner's
-- already-open phone rather than waiting for them to reload. Menu edits are
-- rare, so the cost of carrying them is nothing next to the confusion of a
-- customer ordering something that was taken off five minutes ago.
alter table public.categories        replica identity full;
alter table public.menu_items        replica identity full;
alter table public.restaurant_tables replica identity full;
alter table public.restaurants       replica identity full;

do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'orders', 'order_items',
    'categories', 'menu_items', 'restaurant_tables', 'restaurants'
  ] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and tablename = v_table
    ) then
      execute format('alter publication supabase_realtime add table public.%I',
                     v_table);
    end if;
  end loop;
end $$;

-- >>>>>>>>>>>>>>>>>>>>>>  0002_policies.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — row level security
-- ============================================================================
--
--  The shape of it:
--
--    * Menus, tables and restaurant profiles are world-readable. A diner scans
--      a sticker and must be able to read the menu before they are anyone.
--    * Orders are readable by the staff of that restaurant, and by the diner
--      who placed them. Nobody else.
--    * Nothing is written directly. Every mutation goes through a SECURITY
--      DEFINER function in 0003_rpc.sql that checks the caller's role and the
--      order's state first. That is why you will find no INSERT or UPDATE
--      policy on `orders` below — the absence is deliberate, not an oversight.
--
--  Doing it this way means the state machine (Rule 6, Rule 7, cancel-only-
--  while-queued) is enforced in one place in the database, instead of being
--  reconstructed out of CHECK constraints and per-column policies.
-- ============================================================================

alter table public.restaurants       enable row level security;
alter table public.staff             enable row level security;
alter table public.categories        enable row level security;
alter table public.menu_items        enable row level security;
alter table public.restaurant_tables enable row level security;
alter table public.orders            enable row level security;
alter table public.order_items       enable row level security;

-- ----------------------------------------------------------------- helpers

-- Which restaurant the caller works for, or null if they are a diner.
--
-- SECURITY DEFINER so it can read `staff` without tripping the policies on
-- `staff`, which would otherwise recurse: the policy needs the function and
-- the function needs the table. `search_path` is pinned so the function cannot
-- be redirected at a shadowed table.
create or replace function public.current_restaurant_id()
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select restaurant_id from public.staff
  where id = auth.uid() and active
$$;

create or replace function public.current_staff_role()
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select role from public.staff
  where id = auth.uid() and active
$$;

-- Admin is a superset: in a small shop the owner works the kitchen and the
-- till as well. Mirrors StaffRole in lib/models/staff_account.dart.
--
-- Every one of these coalesces to false, and that is load-bearing. For a caller
-- who is not staff at all, current_staff_role() is NULL, and `NULL = 'ADMIN'`
-- is NULL rather than false. The guards read `if not can_manage_restaurant()
-- then raise`, and `if NULL then` does not take the branch — so without the
-- coalesce an anonymous caller walks straight past the permission check and is
-- stopped only by whatever constraint happens to catch them further down.
create or replace function public.can_manage_restaurant()
returns boolean language sql stable
set search_path = public, pg_temp
as $$ select coalesce(public.current_staff_role() = 'ADMIN', false) $$;

create or replace function public.can_work_kitchen()
returns boolean language sql stable
set search_path = public, pg_temp
as $$ select coalesce(public.current_staff_role() in ('ADMIN','KITCHEN'), false) $$;

create or replace function public.can_take_payment()
returns boolean language sql stable
set search_path = public, pg_temp
as $$ select coalesce(public.current_staff_role() in ('ADMIN','CASHIER'), false) $$;

grant execute on function public.current_restaurant_id() to anon, authenticated;
grant execute on function public.current_staff_role()   to anon, authenticated;
grant execute on function public.can_manage_restaurant() to anon, authenticated;
grant execute on function public.can_work_kitchen()      to anon, authenticated;
grant execute on function public.can_take_payment()      to anon, authenticated;

-- ------------------------------------------------------------- restaurants

-- Public: a diner needs the name, logo, currency and payment methods to read
-- a menu and a receipt. None of that is a secret.
drop policy if exists restaurants_read on public.restaurants;
create policy restaurants_read on public.restaurants
  for select using (true);

-- Only an admin, and only their own restaurant. `next_order_number` is
-- protected separately by a trigger below.
drop policy if exists restaurants_admin_update on public.restaurants;
create policy restaurants_admin_update on public.restaurants
  for update
  using  (id = public.current_restaurant_id() and public.can_manage_restaurant())
  with check (id = public.current_restaurant_id() and public.can_manage_restaurant());

-- An admin editing settings must not be able to rewind the order counter, or
-- change the slug that is already printed on every table.
--
-- This used to revert next_order_number inside a trigger, which was a bad way
-- to say it: the trigger fires on *every* update to the row, including
-- next_order_number()'s own increment, so the counter never advanced. Every
-- order came out with the same number and the second one ever placed died on
-- the (restaurant_id, order_number) unique constraint.
--
-- Column privileges say it properly. A client simply has no UPDATE right on
-- next_order_number, so it cannot try; and next_order_number() is SECURITY
-- DEFINER, so it is unaffected. The trigger is left holding only the slug,
-- which nothing legitimate ever updates.
revoke update on public.restaurants from anon, authenticated;
grant update (
  name, name_km, logo, phone, address,
  currency_symbol, currency_code, payment_methods
) on public.restaurants to authenticated;

create or replace function public.protect_order_counter()
returns trigger language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.slug is distinct from old.slug then
    raise exception 'A restaurant slug cannot be changed once QR codes are printed';
  end if;
  return new;
end $$;

drop trigger if exists restaurants_protect_counter on public.restaurants;
create trigger restaurants_protect_counter
  before update on public.restaurants
  for each row execute function public.protect_order_counter();

-- ------------------------------------------------------------------- staff

-- Staff may see their colleagues; the PIN pad lists kitchen and cashier names
-- to tap. No secrets live here — passwords are Supabase Auth's problem.
drop policy if exists staff_read on public.staff;
create policy staff_read on public.staff
  for select using (restaurant_id = public.current_restaurant_id());

-- Creating and deleting staff also creates and deletes auth users, so it runs
-- through RPCs rather than direct writes. Admins may rename and deactivate.
drop policy if exists staff_admin_update on public.staff;
create policy staff_admin_update on public.staff
  for update
  using  (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant())
  with check (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant());

-- Moving someone to another restaurant, or promoting them to admin by hand, is
-- not an edit — it is a different account. That used to be a `role = (select
-- role from staff ...)` clause in the policy above, which Postgres refuses:
-- reading `staff` from inside a policy on `staff` is infinite recursion, and
-- every rename failed with 42P17. A trigger sees both OLD and NEW without
-- querying anything, so it says the same thing without the recursion — and it
-- holds for the SECURITY DEFINER functions too, which policies do not touch.
create or replace function public.protect_staff_identity()
returns trigger language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.role is distinct from old.role then
    raise exception
      'A role cannot be changed — delete the account and create it again';
  end if;
  if new.restaurant_id is distinct from old.restaurant_id then
    raise exception 'An account cannot be moved to another restaurant';
  end if;
  if new.id is distinct from old.id then
    raise exception 'An account id cannot be changed';
  end if;
  return new;
end $$;

drop trigger if exists staff_protect_identity on public.staff;
create trigger staff_protect_identity
  before update on public.staff
  for each row execute function public.protect_staff_identity();

-- --------------------------------------------------- menu, categories, tables

-- Public read: this is the menu a diner scans for.
drop policy if exists categories_read on public.categories;
create policy categories_read on public.categories for select using (true);

drop policy if exists menu_items_read on public.menu_items;
create policy menu_items_read on public.menu_items for select using (true);

drop policy if exists tables_read on public.restaurant_tables;
create policy tables_read on public.restaurant_tables for select using (true);

-- Admin-only writes, scoped to their own restaurant. `with check` on insert
-- and update is what stops a client planting a row in another restaurant.
drop policy if exists categories_admin_write on public.categories;
create policy categories_admin_write on public.categories
  for all
  using  (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant())
  with check (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant());

drop policy if exists menu_items_admin_write on public.menu_items;
create policy menu_items_admin_write on public.menu_items
  for all
  using  (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant())
  with check (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant());

drop policy if exists tables_admin_write on public.restaurant_tables;
create policy tables_admin_write on public.restaurant_tables
  for all
  using  (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant())
  with check (restaurant_id = public.current_restaurant_id()
          and public.can_manage_restaurant());

-- ------------------------------------------------------------------ orders

-- Staff see every order in their own restaurant. A diner sees the orders they
-- placed, and nothing else — not the table's, not the restaurant's.
--
-- Deliberately no INSERT, UPDATE or DELETE policy: every write goes through
-- the functions in 0003_rpc.sql, which check role and state first.
drop policy if exists orders_read on public.orders;
create policy orders_read on public.orders
  for select using (
    restaurant_id = public.current_restaurant_id()
    or (customer_id is not null and customer_id = auth.uid())
  );

drop policy if exists order_items_read on public.order_items;
create policy order_items_read on public.order_items
  for select using (
    exists (
      select 1 from public.orders o
      where o.id = order_items.order_id
        and (
          o.restaurant_id = public.current_restaurant_id()
          or (o.customer_id is not null and o.customer_id = auth.uid())
        )
    )
  );

-- >>>>>>>>>>>>>>>>>>>>>>  0003_rpc.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — the mutations
-- ============================================================================
--
--  Every write to an order goes through one of these. They are SECURITY
--  DEFINER, so they can write tables that have no INSERT/UPDATE policy at all,
--  and each one checks the caller's role and the order's current state before
--  it does. That puts the rules the app is built on in exactly one place:
--
--    Rule 6   kitchen owns NEW -> COOKING -> READY
--    Rule 7   cashier owns READY -> PAID -> COMPLETED
--    Rule 12  order numbers are unique per restaurant
--             an order may only be edited or cancelled while still queued
--
--  The client mirrors these checks so it can grey out a button, but the client
--  is not what enforces them.
-- ============================================================================

-- ------------------------------------------------------------ order numbers

-- Rule 12. The UPDATE takes a row lock, so two tills submitting at the same
-- instant get different numbers rather than a duplicate-key error.
create or replace function public.next_order_number(p_restaurant_id uuid)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_number integer;
begin
  update public.restaurants
     set next_order_number = next_order_number + 1
   where id = p_restaurant_id
   returning next_order_number - 1 into v_number;

  if v_number is null then
    raise exception 'Unknown restaurant';
  end if;
  return v_number;
end $$;

revoke execute on function public.next_order_number(uuid) from anon, authenticated;

-- ------------------------------------------------------------- place_order

-- Used by a diner on their own phone and by a cashier at the counter. The
-- difference is p_placed_by: null when the customer placed it themselves.
--
-- p_items is a JSON array of {food_id, name, name_km, price, quantity, note}.
-- Prices are taken from the menu here, not from the client, so a tampered
-- client cannot order a $12 dish for 1 cent.
create or replace function public.place_order(
  p_restaurant_id uuid,
  p_type          text,
  p_table_id      uuid,
  p_note          text,
  p_items         jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order_id     uuid;
  v_number       integer;
  v_table_number text;
  v_subtotal     numeric(10,2) := 0;
  v_placed_by    text;
  v_item         jsonb;
  v_price        numeric(10,2);
  v_available    boolean;
  v_name         text;
  v_name_km      text;
  v_quantity     integer;
begin
  if p_type not in ('DINE_IN','TAKEAWAY') then
    raise exception 'An order is either DINE_IN or TAKEAWAY';
  end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'The cart is empty';
  end if;

  -- Rule 11: a dine-in order carries its table; takeaway carries none.
  if p_type = 'DINE_IN' then
    select number into v_table_number
      from public.restaurant_tables
     where id = p_table_id and restaurant_id = p_restaurant_id;
    if v_table_number is null then
      raise exception 'No table selected — scan a table QR first';
    end if;
  else
    p_table_id := null;
  end if;

  -- A member of staff placing this is taking it at the counter. Anyone else
  -- is the customer, and their order is tagged with their anonymous uid so
  -- they can watch it without an account.
  if public.current_restaurant_id() = p_restaurant_id then
    if not public.can_take_payment() then
      raise exception 'You are not allowed to take an order for a customer';
    end if;
    select name into v_placed_by from public.staff where id = auth.uid();
  end if;

  v_number := public.next_order_number(p_restaurant_id);

  insert into public.orders (
    restaurant_id, order_number, type, table_id, table_number,
    status, customer_note, placed_by, customer_id
  ) values (
    p_restaurant_id, v_number, p_type, p_table_id, v_table_number,
    'NEW', nullif(trim(coalesce(p_note,'')), ''), v_placed_by,
    case when v_placed_by is null then auth.uid() end
  )
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_quantity := greatest(1, coalesce((v_item->>'quantity')::integer, 1));

    -- Rule 9, and the price, both read from the menu rather than trusted.
    select
        case when discount_percent > 0
             then round(price * (100 - discount_percent) / 100.0, 2)
             else price end,
        available, name, name_km
      into v_price, v_available, v_name, v_name_km
      from public.menu_items
     where id = (v_item->>'food_id')::uuid
       and restaurant_id = p_restaurant_id;

    if v_price is null then
      raise exception 'That dish is not on this menu';
    end if;
    if not v_available then
      raise exception '% is sold out', v_name;
    end if;

    insert into public.order_items
      (order_id, food_id, name, name_km, price, quantity, note)
    values
      (v_order_id, (v_item->>'food_id')::uuid, v_name, v_name_km,
       v_price, v_quantity, nullif(trim(coalesce(v_item->>'note','')), ''));

    v_subtotal := v_subtotal + v_price * v_quantity;
  end loop;

  update public.orders
     set subtotal = v_subtotal, total = v_subtotal
   where id = v_order_id;

  return v_order_id;
end $$;

grant execute on function
  public.place_order(uuid, text, uuid, text, jsonb) to anon, authenticated;

-- ------------------------------------------------------- status transitions

-- Shared by all four transitions: find the order, check it belongs to the
-- caller's restaurant, and check it is where it is expected to be.
create or replace function public.assert_transition(
  p_order_id uuid,
  p_from     text
)
returns public.orders
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
begin
  select * into v_order from public.orders where id = p_order_id;
  if v_order.id is null then
    raise exception 'Unknown order';
  end if;
  if v_order.restaurant_id is distinct from public.current_restaurant_id() then
    raise exception 'That order belongs to another restaurant';
  end if;
  if v_order.status <> p_from then
    raise exception 'Order #% is %, it cannot move from %',
      v_order.order_number, v_order.status, p_from;
  end if;
  return v_order;
end $$;

revoke execute on function public.assert_transition(uuid, text) from anon, authenticated;

-- Rule 6 — kitchen owns NEW -> COOKING -> READY.
create or replace function public.start_cooking(p_order_id uuid)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can_work_kitchen() then
    raise exception 'You are not allowed to work the kitchen';
  end if;
  perform public.assert_transition(p_order_id, 'NEW');
  update public.orders set status = 'COOKING' where id = p_order_id;
end $$;

create or replace function public.mark_ready(p_order_id uuid)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can_work_kitchen() then
    raise exception 'You are not allowed to work the kitchen';
  end if;
  perform public.assert_transition(p_order_id, 'COOKING');
  update public.orders set status = 'READY' where id = p_order_id;
end $$;

-- Rule 7 — cashier owns READY -> PAID -> COMPLETED.
create or replace function public.collect_payment(
  p_order_id uuid,
  p_method   text
)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
begin
  if not public.can_take_payment() then
    raise exception 'You are not allowed to take payment';
  end if;
  v_order := public.assert_transition(p_order_id, 'READY');

  -- Rule 10: only a method this restaurant actually accepts.
  if not exists (
    select 1 from public.restaurants
     where id = v_order.restaurant_id and p_method = any(payment_methods)
  ) then
    raise exception '% is not a payment method this restaurant accepts', p_method;
  end if;

  update public.orders
     set status = 'PAID', payment_method = p_method, paid_at = now()
   where id = p_order_id;
end $$;

create or replace function public.complete_order(p_order_id uuid)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can_take_payment() then
    raise exception 'You are not allowed to close an order';
  end if;
  perform public.assert_transition(p_order_id, 'PAID');
  update public.orders set status = 'COMPLETED' where id = p_order_id;
end $$;

-- Only while it is still queued: once a pan is on the heat the dish exists
-- whether or not it is still wanted.
create or replace function public.cancel_order(p_order_id uuid)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
  v_name  text;
begin
  if not public.can_take_payment() then
    raise exception 'You are not allowed to cancel an order';
  end if;
  v_order := public.assert_transition(p_order_id, 'NEW');
  select name into v_name from public.staff where id = auth.uid();

  update public.orders
     set status = 'CANCELLED', cancelled_by = v_name, cancelled_at = now()
   where id = p_order_id;
end $$;

grant execute on function public.start_cooking(uuid)          to authenticated;
grant execute on function public.mark_ready(uuid)             to authenticated;
grant execute on function public.collect_payment(uuid, text)  to authenticated;
grant execute on function public.complete_order(uuid)         to authenticated;
grant execute on function public.cancel_order(uuid)           to authenticated;

-- --------------------------------------------------------- editing an order

-- A quantity of zero drops the line. Removing the last one is refused: an
-- order with nothing on it is not something the kitchen or the till can act
-- on, so that case is a cancellation and has to be made as one.
create or replace function public.set_order_item_quantity(
  p_order_id uuid,
  p_item_id  uuid,
  p_quantity integer
)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
  v_count integer;
begin
  if not public.can_take_payment() then
    raise exception 'You are not allowed to change an order';
  end if;
  v_order := public.assert_transition(p_order_id, 'NEW');

  if not exists (
    select 1 from public.order_items
     where id = p_item_id and order_id = p_order_id
  ) then
    raise exception 'That dish is not on this order';
  end if;

  select count(*) into v_count from public.order_items where order_id = p_order_id;

  if p_quantity <= 0 then
    if v_count <= 1 then
      raise exception
        'That is the only dish left — cancel order #% instead',
        v_order.order_number;
    end if;
    delete from public.order_items where id = p_item_id;
  else
    update public.order_items set quantity = p_quantity where id = p_item_id;
  end if;

  update public.orders o
     set subtotal = c.sum, total = c.sum
    from (
      select coalesce(sum(price * quantity), 0)::numeric(10,2) as sum
        from public.order_items where order_id = p_order_id
    ) c
   where o.id = p_order_id;
end $$;

grant execute on function
  public.set_order_item_quantity(uuid, uuid, integer) to authenticated;

-- --------------------------------------------------------- staff directory

-- The PIN pad lists kitchen and cashier names to tap, and it has to do that
-- before anyone is signed in — so this one is deliberately public.
--
-- It exposes staff first names and role for a restaurant whose slug you
-- already know. It exposes no contact details and no secrets; passwords are
-- Supabase Auth's problem and are never in this table. If even the names are
-- too much for your setting, drop the grant to `anon` and have staff sign in
-- by typing their username instead.
create or replace function public.staff_directory(p_slug text)
returns table (id uuid, name text, role text)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select s.id, s.name, s.role
    from public.staff s
    join public.restaurants r on r.id = s.restaurant_id
   where r.slug = p_slug
     and s.active
     and s.role <> 'ADMIN'
   order by s.name
$$;

grant execute on function public.staff_directory(text) to anon, authenticated;

-- >>>>>>>>>>>>>>>>>>>>>>  0004_accounts.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — staff accounts
-- ============================================================================
--
--  Staff are real Supabase Auth users, so row level security can trust
--  `auth.uid()`. They never type an email address, though: the app derives one
--  from what they do type.
--
--      admin            <username>@<slug>.staff.ezorder.app
--      kitchen/cashier  <staff-id>@<slug>.staff.ezorder.app
--
--  Both are derivable by the client with no lookup — the admin's from the
--  username they type, everyone else's from the id in staff_directory(). That
--  matters: it means there is no "does this username exist" endpoint to probe.
--
--  Creating an auth user normally needs the service_role key, which must never
--  be in a phone app. These functions are SECURITY DEFINER instead, so an
--  admin signed in with the anon key can create staff for their own restaurant
--  and nobody else's.
-- ============================================================================

-- Derives the login address. Kept in SQL as well as Dart so both agree.
create or replace function public.staff_login_email(
  p_slug  text,
  p_local text
)
returns text language sql immutable
set search_path = public, pg_temp
as $$ select lower(p_local) || '@' || lower(p_slug) || '.staff.ezorder.app' $$;

grant execute on function public.staff_login_email(text, text) to anon, authenticated;

-- ---------------------------------------------------- creating an auth user
--
-- Writes the two rows GoTrue expects: the user, and an `email` identity. The
-- identities table has gained columns across GoTrue versions, so the insert is
-- built dynamically from what actually exists in this project rather than
-- assuming one particular version.
create or replace function public.create_auth_user(
  p_email    text,
  p_password text
)
returns uuid
language plpgsql
security definer
-- `extensions` is on the path because that is where Supabase installs
-- pgcrypto: crypt() and gen_salt() are not in `public` and will not be found
-- without it.
set search_path = public, extensions, auth, pg_temp
as $$
declare
  v_id  uuid := gen_random_uuid();
  v_cols text := 'user_id, identity_data, provider, last_sign_in_at, created_at, updated_at';
  v_vals text := '$1, $2, ''email'', now(), now(), now()';
begin
  if p_password is null or length(p_password) < 6 then
    raise exception 'A password or PIN must be at least 6 characters';
  end if;
  if exists (select 1 from auth.users where lower(email) = lower(p_email)) then
    raise exception 'Another account already uses that username';
  end if;

  insert into auth.users (
    instance_id, id, aud, role, email, encrypted_password,
    email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
    created_at, updated_at,
    confirmation_token, recovery_token, email_change_token_new, email_change
  ) values (
    '00000000-0000-0000-0000-000000000000', v_id, 'authenticated',
    'authenticated', lower(p_email), crypt(p_password, gen_salt('bf')),
    now(), '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb,
    now(), now(), '', '', '', ''
  );

  -- `id` and `provider_id` appeared in later GoTrue versions.
  if exists (select 1 from information_schema.columns
              where table_schema = 'auth' and table_name = 'identities'
                and column_name = 'id') then
    v_cols := 'id, ' || v_cols;
    v_vals := 'gen_random_uuid(), ' || v_vals;
  end if;
  if exists (select 1 from information_schema.columns
              where table_schema = 'auth' and table_name = 'identities'
                and column_name = 'provider_id') then
    v_cols := v_cols || ', provider_id';
    v_vals := v_vals || ', $1::text';
  end if;

  execute format('insert into auth.identities (%s) values (%s)', v_cols, v_vals)
    using v_id, jsonb_build_object('sub', v_id::text, 'email', lower(p_email));

  return v_id;
end $$;

-- Never callable from a client; only from the functions below.
revoke execute on function public.create_auth_user(text, text) from anon, authenticated;

-- ------------------------------------------------------ bootstrap: run once
--
-- Creates a restaurant and its first admin. This is the only function you call
-- by hand, from the SQL editor, because until it has run there is no admin to
-- authorise anything.
--
--   select public.provision_restaurant('demo', 'ABC Restaurant',
--                                      'admin', 'a-long-password');
create or replace function public.provision_restaurant(
  p_slug           text,
  p_name           text,
  p_admin_username text,
  p_admin_password text
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_restaurant_id uuid;
  v_user_id       uuid;
begin
  if length(coalesce(p_admin_password,'')) < 8 then
    raise exception 'Give the owner a password of at least 8 characters';
  end if;

  insert into public.restaurants (slug, name)
  values (lower(p_slug), p_name)
  returning id into v_restaurant_id;

  v_user_id := public.create_auth_user(
    public.staff_login_email(p_slug, p_admin_username), p_admin_password);

  insert into public.staff (id, restaurant_id, name, role, username)
  values (v_user_id, v_restaurant_id, p_name || ' Owner', 'ADMIN',
          lower(p_admin_username));

  return v_restaurant_id;
end $$;

revoke execute on function
  public.provision_restaurant(text, text, text, text) from anon, authenticated;

-- ------------------------------------------------------------ manage staff

create or replace function public.create_staff_account(
  p_name     text,
  p_role     text,
  p_secret   text,
  p_username text default ''
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_restaurant_id uuid := public.current_restaurant_id();
  v_slug          text;
  v_user_id       uuid;
  v_local         text;
begin
  if not public.can_manage_restaurant() then
    raise exception 'You are not allowed to manage staff';
  end if;
  if p_role not in ('ADMIN','KITCHEN','CASHIER') then
    raise exception 'Unknown role %', p_role;
  end if;
  if p_role = 'ADMIN' and length(trim(coalesce(p_username,''))) = 0 then
    raise exception 'An admin needs a username';
  end if;

  select slug into v_slug from public.restaurants where id = v_restaurant_id;

  -- An admin's address comes from their username so they can sign in by
  -- typing it. Everyone else's comes from their id, which the PIN pad already
  -- has from staff_directory().
  if p_role = 'ADMIN' then
    v_local := lower(trim(p_username));
    v_user_id := public.create_auth_user(
      public.staff_login_email(v_slug, v_local), p_secret);
  else
    -- create_auth_user mints the id, so the address is built from a throwaway
    -- value and rewritten to the real id once we have it. The client derives
    -- the same address from staff_directory(), so the two always agree.
    v_user_id := public.create_auth_user(
      public.staff_login_email(v_slug, gen_random_uuid()::text), p_secret);
    update auth.users
       set email = public.staff_login_email(v_slug, v_user_id::text)
     where id = v_user_id;
    update auth.identities
       set identity_data = jsonb_build_object(
             'sub', v_user_id::text,
             'email', public.staff_login_email(v_slug, v_user_id::text))
     where user_id = v_user_id;
  end if;

  insert into public.staff (id, restaurant_id, name, role, username)
  values (v_user_id, v_restaurant_id, trim(p_name), p_role,
          case when p_role = 'ADMIN' then lower(trim(p_username)) else '' end);

  return v_user_id;
end $$;

grant execute on function
  public.create_staff_account(text, text, text, text) to authenticated;

create or replace function public.reset_staff_secret(
  p_staff_id uuid,
  p_secret   text
)
returns void language plpgsql security definer
-- See create_auth_user: pgcrypto lives in `extensions`.
set search_path = public, extensions, auth, pg_temp
as $$
begin
  if not public.can_manage_restaurant() then
    raise exception 'You are not allowed to manage staff';
  end if;
  if not exists (
    select 1 from public.staff
     where id = p_staff_id and restaurant_id = public.current_restaurant_id()
  ) then
    raise exception 'That account is not yours to change';
  end if;
  if length(coalesce(p_secret,'')) < 6 then
    raise exception 'A password or PIN must be at least 6 characters';
  end if;

  update auth.users
     set encrypted_password = crypt(p_secret, gen_salt('bf')), updated_at = now()
   where id = p_staff_id;
end $$;

grant execute on function public.reset_staff_secret(uuid, text) to authenticated;

-- Locking every admin out would be unrecoverable without the SQL editor, so
-- the last active one is protected — same guard the prototype had.
create or replace function public.assert_not_last_admin(p_staff_id uuid)
returns void language plpgsql
set search_path = public, pg_temp
as $$
begin
  if exists (select 1 from public.staff
              where id = p_staff_id and role = 'ADMIN' and active)
     and not exists (
       select 1 from public.staff
        where restaurant_id = public.current_restaurant_id()
          and role = 'ADMIN' and active and id <> p_staff_id
     )
  then
    raise exception 'There must be at least one active admin';
  end if;
end $$;

create or replace function public.set_staff_active(
  p_staff_id uuid,
  p_active   boolean
)
returns void language plpgsql security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can_manage_restaurant() then
    raise exception 'You are not allowed to manage staff';
  end if;
  if not exists (
    select 1 from public.staff
     where id = p_staff_id and restaurant_id = public.current_restaurant_id()
  ) then
    raise exception 'That account is not yours to change';
  end if;
  if not p_active then
    perform public.assert_not_last_admin(p_staff_id);
  end if;

  update public.staff set active = p_active where id = p_staff_id;
end $$;

create or replace function public.delete_staff_account(p_staff_id uuid)
returns void language plpgsql security definer
set search_path = public, auth, pg_temp
as $$
begin
  if not public.can_manage_restaurant() then
    raise exception 'You are not allowed to manage staff';
  end if;
  if p_staff_id = auth.uid() then
    raise exception 'You cannot delete the account you are signed in with';
  end if;
  if not exists (
    select 1 from public.staff
     where id = p_staff_id and restaurant_id = public.current_restaurant_id()
  ) then
    raise exception 'That account is not yours to change';
  end if;
  perform public.assert_not_last_admin(p_staff_id);

  -- staff.id references auth.users on delete cascade, so this removes both.
  delete from auth.users where id = p_staff_id;
end $$;

grant execute on function public.set_staff_active(uuid, boolean) to authenticated;
grant execute on function public.delete_staff_account(uuid)      to authenticated;

-- >>>>>>>>>>>>>>>>>>>>>>  0005_photos.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — dish photos move to Storage
-- ============================================================================
--
--  Photos were base64 in `menu_items.photo`, which meant every menu fetch
--  dragged every photo with it. Measured on a live project: 268 KB of JSON for
--  a single dish. Thirty dishes would be ~8 MB downloaded by every diner, on
--  every load, and would exhaust Supabase's 5 GB monthly egress after about
--  625 menu views.
--
--  A URL into a public Storage bucket is ~90 bytes instead, the image comes
--  from a CDN, and the browser caches it. Menu JSON drops to a couple of KB.
--
--  Run this after 0001–0004. Safe to re-run.
-- ============================================================================

-- The URL replaces the base64. `photo` is kept for now so an app build that
-- has not been updated yet keeps working, and so existing photos survive until
-- they are migrated; see the note at the bottom about dropping it.
alter table public.menu_items
  add column if not exists photo_url text;

-- ------------------------------------------------------------------ bucket

-- Public read: a dish photo is exactly as secret as the menu it is on, which
-- is to say not at all — a diner has to see it before they are anyone.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'menu-photos', 'menu-photos', true, 2097152,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
  set public             = true,
      file_size_limit    = 2097152,
      allowed_mime_types = array['image/jpeg','image/png','image/webp'];

-- ------------------------------------------------------------------ access

-- Files are laid out as `<restaurant_id>/<uuid>.<ext>`, so the first path
-- segment is what scopes a write to the restaurant the caller belongs to.
-- An admin of one restaurant cannot write into another's folder.

drop policy if exists menu_photos_read on storage.objects;
create policy menu_photos_read on storage.objects
  for select using (bucket_id = 'menu-photos');

drop policy if exists menu_photos_insert on storage.objects;
create policy menu_photos_insert on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'menu-photos'
    and public.can_manage_restaurant()
    and (storage.foldername(name))[1] = public.current_restaurant_id()::text
  );

drop policy if exists menu_photos_update on storage.objects;
create policy menu_photos_update on storage.objects
  for update to authenticated
  using (
    bucket_id = 'menu-photos'
    and public.can_manage_restaurant()
    and (storage.foldername(name))[1] = public.current_restaurant_id()::text
  );

drop policy if exists menu_photos_delete on storage.objects;
create policy menu_photos_delete on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'menu-photos'
    and public.can_manage_restaurant()
    and (storage.foldername(name))[1] = public.current_restaurant_id()::text
  );

-- ============================================================================
--  Once every dish has a photo_url and every device is on a build that reads
--  it, the old column can go:
--
--      alter table public.menu_items drop column photo;
--
--  Check first — this must return 0:
--
--      select count(*) from public.menu_items
--       where photo is not null and photo_url is null;
-- ============================================================================

-- >>>>>>>>>>>>>>>>>>>>>>  0006_plans.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — subscription plans
-- ============================================================================
--
--  FREE   $0      5 tables    2 staff   unlimited orders
--  BASIC  $5.99  20 tables    5 staff   unlimited orders
--  PRO    $9.99  unlimited   10 staff   unlimited orders
--
--  Orders are unlimited on every plan on purpose: charging a restaurant per
--  order would punish them for a good night.
--
--  The limits are enforced here, in triggers, rather than in the app. The app
--  keeps its own copy of the numbers so it can grey out a button and show
--  usage, but a patched client that ignores them still cannot get a sixth
--  table into a free restaurant.
--
--  Changing a restaurant's plan is a manual UPDATE for now — there is no
--  payment processing. See the bottom of this file.
--
--  Run after 0001–0005. Safe to re-run.
-- ============================================================================

alter table public.restaurants
  add column if not exists plan text not null default 'FREE';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'restaurants_plan_check'
  ) then
    alter table public.restaurants
      add constraint restaurants_plan_check
      check (plan in ('FREE','BASIC','PRO'));
  end if;
end $$;

comment on column public.restaurants.plan is
  'FREE, BASIC or PRO. Caps tables and staff via the triggers below. Changed '
  'by hand until billing exists; a client cannot write it (see the column '
  'grants in 0002_policies.sql).';

-- ------------------------------------------------------------------ limits

-- One place both triggers read, so the two can never drift apart.
create or replace function public.plan_limits(p_plan text)
returns table (max_tables integer, max_staff integer)
language sql immutable
set search_path = public, pg_temp
as $$
  -- Naming the columns, not `select *`: the values list carries three columns
  -- and this function returns two, so a star would hand back `plan` where
  -- max_tables belongs and fail with a return type mismatch.
  select t.max_tables, t.max_staff
    from (values
      ('FREE',   5,             2),
      ('BASIC',  20,            5),
      -- NULL is unlimited. Not a big number: a cap of 999 is one somebody
      -- eventually hits and cannot explain. Cast, so the column is typed
      -- integer rather than left unknown.
      ('PRO',    null::integer, 10)
    ) as t(plan, max_tables, max_staff)
   where t.plan = p_plan
$$;

grant execute on function public.plan_limits(text) to anon, authenticated;

-- --------------------------------------------------------------- the caps

create or replace function public.enforce_table_limit()
returns trigger language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_plan  text;
  v_limit integer;
  v_count integer;
begin
  select plan into v_plan from public.restaurants where id = new.restaurant_id;
  select max_tables into v_limit from public.plan_limits(v_plan);
  if v_limit is null then
    return new;
  end if;

  select count(*) into v_count
    from public.restaurant_tables
   where restaurant_id = new.restaurant_id;

  if v_count >= v_limit then
    raise exception
      'The % plan allows % tables. Upgrade to add more.', v_plan, v_limit
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists tables_plan_limit on public.restaurant_tables;
create trigger tables_plan_limit
  before insert on public.restaurant_tables
  for each row execute function public.enforce_table_limit();

create or replace function public.enforce_staff_limit()
returns trigger language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_plan  text;
  v_limit integer;
  v_count integer;
begin
  select plan into v_plan from public.restaurants where id = new.restaurant_id;
  select max_staff into v_limit from public.plan_limits(v_plan);
  if v_limit is null then
    return new;
  end if;

  -- Counts everyone with an account, including the owner and anyone switched
  -- off. A deactivated account still occupies a seat: it can be switched back
  -- on, and counting only active staff would make the cap trivially evadable.
  select count(*) into v_count
    from public.staff
   where restaurant_id = new.restaurant_id;

  if v_count >= v_limit then
    raise exception
      'The % plan allows % staff accounts. Upgrade to add more.', v_plan, v_limit
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists staff_plan_limit on public.staff;
create trigger staff_plan_limit
  before insert on public.staff
  for each row execute function public.enforce_staff_limit();

-- ------------------------------------------------------------------ usage

-- What the admin screen shows. A function rather than a view so it can be
-- granted on its own, and so a caller only ever sees their own restaurant.
create or replace function public.plan_usage()
returns table (
  plan        text,
  tables_used integer,
  max_tables  integer,
  staff_used  integer,
  max_staff   integer
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select
    r.plan,
    (select count(*)::integer from public.restaurant_tables t
      where t.restaurant_id = r.id),
    l.max_tables,
    (select count(*)::integer from public.staff s
      where s.restaurant_id = r.id),
    l.max_staff
  from public.restaurants r
  cross join lateral public.plan_limits(r.plan) l
  where r.id = public.current_restaurant_id()
$$;

grant execute on function public.plan_usage() to authenticated;

-- ------------------------------------------------------- who may change it

-- The column grants in 0002 list exactly what a client may update, and `plan`
-- is not among them — so an admin cannot promote their own restaurant from
-- the settings screen. Re-stated here so the grant survives a re-run of that
-- file in either order.
revoke update on public.restaurants from anon, authenticated;
grant update (
  name, name_km, logo, phone, address,
  currency_symbol, currency_code, payment_methods
) on public.restaurants to authenticated;

-- ============================================================================
--  Changing a plan, until billing exists:
--
--      update public.restaurants set plan = 'BASIC' where slug = 'demo';
--
--  Downgrading does not delete anything. A restaurant that drops from PRO to
--  FREE with 30 tables keeps all 30 and simply cannot add a 31st — throwing
--  away a paying customer's data because their card expired would be a far
--  worse bug than a cap that is temporarily over.
-- ============================================================================

-- >>>>>>>>>>>>>>>>>>>>>>  0007_hardening.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — hardening
-- ============================================================================
--
--  Run after 0001–0006. Safe to re-run.
-- ============================================================================

-- --------------------------------------------------- the order counter leak
--
-- `restaurants` is world-readable, which it has to be: a diner scans a sticker
-- and needs the name, logo and currency before they are anyone. But `select *`
-- also handed out `next_order_number`, and that is a business metric — anyone
-- could poll it and watch how many orders a restaurant takes in a day, for
-- every restaurant in the project.
--
-- Column grants fix it without touching the policy. The client now names the
-- columns it wants, and next_order_number is not among them.
-- next_order_number() is SECURITY DEFINER, so it is unaffected.

revoke select on public.restaurants from anon, authenticated;
grant select (
  id, slug, name, name_km, logo, phone, address,
  currency_symbol, currency_code, payment_methods, plan, created_at
) on public.restaurants to anon, authenticated;

-- ============================================================================
--  Still open, and deliberately not "fixed" here because the fix is a product
--  decision rather than a line of SQL:
--
--  1. THE CUSTOMER LIST IS PUBLIC. `restaurants` has `using (true)`, so anyone
--     with the anon key can list every restaurant on this project. That is
--     fine while it is your own restaurants; it is not fine once you are
--     selling to competitors of each other. The fix is to stop selecting the
--     table directly and go through a SECURITY DEFINER function that takes a
--     slug and returns exactly one row.
--
--  2. STAFF PINS ARE BRUTE-FORCEABLE IN PRINCIPLE. staff_directory() is public
--     — the PIN pad has to list names before anyone is signed in — and it
--     returns the staff id, from which the login address is derived by a rule
--     both the app and 0004 know. So an attacker knows a valid username and
--     needs only six digits: a million combinations, and no account lockout.
--     Supabase rate-limits auth per IP, which makes this slow rather than
--     impossible.
--
--     The honest fixes, in order of effort:
--       * raise StaffAccount.pinLength to 8 (one line, but every existing PIN
--         must be re-issued),
--       * lock an account for a few minutes after a run of failures,
--       * stop returning the staff id publicly and have the pad exchange an
--         opaque token instead.
-- ============================================================================

-- >>>>>>>>>>>>>>>>>>>>>>  0008_platform.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — the platform operator's console
-- ============================================================================
--
--  A second, separate audience: you, running the service, rather than a
--  restaurant running its floor. Platform admins are not staff of any
--  restaurant, so they get their own table rather than a flag on `staff`.
--
--  Everything the console does goes through the SECURITY DEFINER functions
--  below. It never selects a merchant's tables directly, and none of these
--  functions returns an individual order, item or customer note — only counts
--  and totals. That is a deliberate limit: you can bill and support a merchant
--  without being able to read what a particular diner ate, and it is a far
--  easier answer to give when a merchant asks what you can see.
--
--  Run after 0001–0007. Safe to re-run.
-- ============================================================================

-- --------------------------------------------------------- who runs the show

create table if not exists public.platform_admins (
  id         uuid primary key references auth.users(id) on delete cascade,
  name       text not null default '',
  created_at timestamptz not null default now()
);

alter table public.platform_admins enable row level security;

-- No policy at all: nothing reads this table from a client. The only thing
-- that consults it is is_platform_admin(), which is SECURITY DEFINER and so
-- bypasses RLS. A restaurant admin cannot read the list, and — more to the
-- point — cannot add themselves to it.
--
-- Membership is granted by hand, in the SQL editor. See the bottom of the file.

create or replace function public.is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  -- coalesce, because `exists` on no rows for an unauthenticated caller must
  -- be false rather than null. The same NULL-versus-false mistake in the
  -- restaurant guards let an anonymous caller walk past a permission check.
  select coalesce(
    (select true from public.platform_admins where id = auth.uid()), false)
$$;

grant execute on function public.is_platform_admin() to anon, authenticated;

-- ------------------------------------------------------------- suspension

alter table public.restaurants
  add column if not exists suspended boolean not null default false;

comment on column public.restaurants.suspended is
  'Set by the platform console. Stops new orders; staff can still sign in and '
  'read their history, because freezing a restaurant should not also delete '
  'their access to yesterday''s takings.';

-- The ordering path is the thing that stops. Staff keep their access on
-- purpose: a merchant who has fallen behind on payment still needs to close
-- out the orders already on their floor, and locking them out of their own
-- history would be punitive rather than persuasive.
create or replace function public.assert_not_suspended(p_restaurant_id uuid)
returns void
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if exists (
    select 1 from public.restaurants
     where id = p_restaurant_id and suspended
  ) then
    raise exception
      'This restaurant is not accepting orders at the moment.'
      using errcode = 'check_violation';
  end if;
end $$;

grant execute on function public.assert_not_suspended(uuid) to anon, authenticated;

-- ------------------------------------------------------------- the console

-- One row per merchant: what they are on, what they are using, what they have
-- taken. Counts and totals only.
create or replace function public.platform_overview()
returns table (
  id            uuid,
  slug          text,
  name          text,
  plan          text,
  suspended     boolean,
  created_at    timestamptz,
  tables_used   integer,
  max_tables    integer,
  staff_used    integer,
  max_staff     integer,
  orders_total  integer,
  orders_today  integer,
  revenue_total numeric,
  revenue_today numeric,
  last_order_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_platform_admin() then
    raise exception 'Not a platform administrator';
  end if;

  return query
  select
    r.id, r.slug, r.name, r.plan, r.suspended, r.created_at,
    (select count(*)::integer from public.restaurant_tables t
      where t.restaurant_id = r.id),
    l.max_tables,
    (select count(*)::integer from public.staff s
      where s.restaurant_id = r.id),
    l.max_staff,
    (select count(*)::integer from public.orders o
      where o.restaurant_id = r.id),
    (select count(*)::integer from public.orders o
      where o.restaurant_id = r.id
        and o.created_at >= date_trunc('day', now())),
    -- Only money actually taken. An order on the stove has earned nothing yet,
    -- and a cancelled one never will.
    (select coalesce(sum(o.total), 0) from public.orders o
      where o.restaurant_id = r.id and o.status in ('PAID','COMPLETED')),
    (select coalesce(sum(o.total), 0) from public.orders o
      where o.restaurant_id = r.id and o.status in ('PAID','COMPLETED')
        and o.created_at >= date_trunc('day', now())),
    (select max(o.created_at) from public.orders o
      where o.restaurant_id = r.id)
  from public.restaurants r
  cross join lateral public.plan_limits(r.plan) l
  order by r.created_at;
end $$;

grant execute on function public.platform_overview() to authenticated;

-- Signing up a customer, without anybody pasting SQL.
create or replace function public.platform_create_merchant(
  p_slug           text,
  p_name           text,
  p_admin_username text,
  p_admin_password text
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_platform_admin() then
    raise exception 'Not a platform administrator';
  end if;
  return public.provision_restaurant(
    p_slug, p_name, p_admin_username, p_admin_password);
end $$;

grant execute on function
  public.platform_create_merchant(text, text, text, text) to authenticated;

create or replace function public.platform_set_plan(
  p_restaurant_id uuid,
  p_plan          text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_platform_admin() then
    raise exception 'Not a platform administrator';
  end if;
  if p_plan not in ('FREE','BASIC','PRO') then
    raise exception 'Unknown plan %', p_plan;
  end if;

  -- Downgrading deletes nothing. A merchant dropping to FREE with thirty
  -- tables keeps all thirty and simply cannot add a thirty-first.
  update public.restaurants set plan = p_plan where id = p_restaurant_id;
  if not found then
    raise exception 'Unknown restaurant';
  end if;
end $$;

create or replace function public.platform_set_suspended(
  p_restaurant_id uuid,
  p_suspended     boolean
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_platform_admin() then
    raise exception 'Not a platform administrator';
  end if;
  update public.restaurants set suspended = p_suspended
   where id = p_restaurant_id;
  if not found then
    raise exception 'Unknown restaurant';
  end if;
end $$;

grant execute on function public.platform_set_plan(uuid, text) to authenticated;
grant execute on function
  public.platform_set_suspended(uuid, boolean) to authenticated;

-- ------------------------------------------- suspension bites where it counts

-- place_order is redefined here rather than in 0003 so the suspension check
-- lives beside the thing that introduced it. Identical to 0003 apart from the
-- one guard at the top: a flag nothing consults is decoration.
create or replace function public.place_order(
  p_restaurant_id uuid,
  p_type          text,
  p_table_id      uuid,
  p_note          text,
  p_items         jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order_id     uuid;
  v_number       integer;
  v_table_number text;
  v_subtotal     numeric(10,2) := 0;
  v_placed_by    text;
  v_item         jsonb;
  v_price        numeric(10,2);
  v_available    boolean;
  v_name         text;
  v_name_km      text;
  v_quantity     integer;
begin
  perform public.assert_not_suspended(p_restaurant_id);

  if p_type not in ('DINE_IN','TAKEAWAY') then
    raise exception 'An order is either DINE_IN or TAKEAWAY';
  end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'The cart is empty';
  end if;

  if p_type = 'DINE_IN' then
    select number into v_table_number
      from public.restaurant_tables
     where id = p_table_id and restaurant_id = p_restaurant_id;
    if v_table_number is null then
      raise exception 'No table selected — scan a table QR first';
    end if;
  else
    p_table_id := null;
  end if;

  if public.current_restaurant_id() = p_restaurant_id then
    if not public.can_take_payment() then
      raise exception 'You are not allowed to take an order for a customer';
    end if;
    select name into v_placed_by from public.staff where id = auth.uid();
  end if;

  v_number := public.next_order_number(p_restaurant_id);

  insert into public.orders (
    restaurant_id, order_number, type, table_id, table_number,
    status, customer_note, placed_by, customer_id
  ) values (
    p_restaurant_id, v_number, p_type, p_table_id, v_table_number,
    'NEW', nullif(trim(coalesce(p_note,'')), ''), v_placed_by,
    case when v_placed_by is null then auth.uid() end
  )
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_quantity := greatest(1, coalesce((v_item->>'quantity')::integer, 1));

    select
        case when discount_percent > 0
             then round(price * (100 - discount_percent) / 100.0, 2)
             else price end,
        available, name, name_km
      into v_price, v_available, v_name, v_name_km
      from public.menu_items
     where id = (v_item->>'food_id')::uuid
       and restaurant_id = p_restaurant_id;

    if v_price is null then
      raise exception 'That dish is not on this menu';
    end if;
    if not v_available then
      raise exception '% is sold out', v_name;
    end if;

    insert into public.order_items
      (order_id, food_id, name, name_km, price, quantity, note)
    values
      (v_order_id, (v_item->>'food_id')::uuid, v_name, v_name_km,
       v_price, v_quantity, nullif(trim(coalesce(v_item->>'note','')), ''));

    v_subtotal := v_subtotal + v_price * v_quantity;
  end loop;

  update public.orders
     set subtotal = v_subtotal, total = v_subtotal
   where id = v_order_id;

  return v_order_id;
end $$;

grant execute on function
  public.place_order(uuid, text, uuid, text, jsonb) to anon, authenticated;

-- ============================================================================
--  Making yourself a platform administrator
--
--  1. Create the account. Authentication → Users → Add user, with a real email
--     and password, and tick "Auto Confirm User".
--
--  2. Then, here:
--
--         insert into public.platform_admins (id, name)
--         select id, 'Your Name' from auth.users where email = 'you@example.com'
--         on conflict (id) do nothing;
--
--  There is deliberately no way to do this from any app. The table has RLS on
--  and no policy, so the only route in is the SQL editor — which means an
--  attacker needs your database credentials, not merely an account.
-- ============================================================================

-- >>>>>>>>>>>>>>>>>>>>>>  0009_platform_detail.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — more for the operator to go on
-- ============================================================================
--
--  The first version of platform_overview() answered "how big is each
--  merchant". That is the wrong first question. Running a service, what you
--  need to know is which merchants need something from you:
--
--    * signed up and never finished setting up — no menu, or no tables, so
--      they physically cannot take an order and probably do not know why
--    * set up and never took an order — onboarding worked, adoption did not
--    * were busy and have gone quiet — the shape of churn
--    * pressed against a plan limit — the shape of an upgrade
--
--  So this adds setup completeness, a recent-versus-previous week comparison,
--  and the contact details you would need to actually pick up the phone.
--
--  Still aggregates only: no order, no item, no customer note.
--
--  Run after 0008. Safe to re-run.
-- ============================================================================

-- The return type changes, and `create or replace` cannot alter one.
drop function if exists public.platform_overview();

create function public.platform_overview()
returns table (
  id             uuid,
  slug           text,
  name           text,
  logo           text,
  phone          text,
  address        text,
  plan           text,
  suspended      boolean,
  created_at     timestamptz,
  tables_used    integer,
  max_tables     integer,
  staff_used     integer,
  max_staff      integer,
  categories     integer,
  menu_items     integer,
  orders_total   integer,
  orders_today   integer,
  orders_7d      integer,
  orders_prev_7d integer,
  revenue_total  numeric,
  revenue_today  numeric,
  revenue_30d    numeric,
  last_order_at  timestamptz,
  owner_username text
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_platform_admin() then
    raise exception 'Not a platform administrator';
  end if;

  return query
  select
    r.id, r.slug, r.name, r.logo, r.phone, r.address,
    r.plan, r.suspended, r.created_at,

    (select count(*)::integer from public.restaurant_tables t
      where t.restaurant_id = r.id),
    l.max_tables,
    (select count(*)::integer from public.staff s
      where s.restaurant_id = r.id),
    l.max_staff,

    -- Setup completeness. A restaurant with no category, no dish or no table
    -- cannot take an order at all, however long ago they signed up.
    (select count(*)::integer from public.categories c
      where c.restaurant_id = r.id),
    (select count(*)::integer from public.menu_items m
      where m.restaurant_id = r.id),

    (select count(*)::integer from public.orders o
      where o.restaurant_id = r.id),
    (select count(*)::integer from public.orders o
      where o.restaurant_id = r.id
        and o.created_at >= date_trunc('day', now())),
    -- This week against the week before it: one number is a fact, two are a
    -- direction.
    (select count(*)::integer from public.orders o
      where o.restaurant_id = r.id
        and o.created_at >= now() - interval '7 days'),
    (select count(*)::integer from public.orders o
      where o.restaurant_id = r.id
        and o.created_at >= now() - interval '14 days'
        and o.created_at <  now() - interval '7 days'),

    -- Only money actually taken.
    (select coalesce(sum(o.total), 0) from public.orders o
      where o.restaurant_id = r.id and o.status in ('PAID','COMPLETED')),
    (select coalesce(sum(o.total), 0) from public.orders o
      where o.restaurant_id = r.id and o.status in ('PAID','COMPLETED')
        and o.created_at >= date_trunc('day', now())),
    (select coalesce(sum(o.total), 0) from public.orders o
      where o.restaurant_id = r.id and o.status in ('PAID','COMPLETED')
        and o.created_at >= now() - interval '30 days'),

    (select max(o.created_at) from public.orders o
      where o.restaurant_id = r.id),

    -- Who to address an email to. Not a contact address — the owner signs in
    -- with a username, and this app never asked them for a real one.
    (select s.username from public.staff s
      where s.restaurant_id = r.id and s.role = 'ADMIN' and s.username <> ''
      order by s.created_at limit 1)

  from public.restaurants r
  cross join lateral public.plan_limits(r.plan) l
  order by r.created_at;
end $$;

grant execute on function public.platform_overview() to authenticated;

-- >>>>>>>>>>>>>>>>>>>>>>  0010_upgrades.sql  <<<<<<<<<<<<<<<<<<<<<<

-- ============================================================================
--  EZ Order — upgrade requests
-- ============================================================================
--
--  There is no billing. A merchant who wants a bigger plan has to reach you,
--  and until this file the only thing that happened when they hit a plan limit
--  was a red error message. That is a merchant standing at the counter with
--  money in their hand and nobody behind the till.
--
--  So: one row per merchant who has asked. They tap once, it lands here, and
--  the console shows it as a queue. The same row is what the app reads back to
--  say "we have your request, we will call you on 012 345 678" — a request
--  that vanishes feels exactly like being ignored.
--
--  Two rules worth stating up front:
--
--    * **One open request per merchant.** Tapping again edits the request
--      rather than filing a second one. A support queue with four copies of
--      the same ask is worse than no queue.
--    * **The plan change resolves it.** Moving a merchant onto the plan they
--      asked for closes their request automatically, because the alternative
--      is a queue full of things already done.
--
--  Run after 0001–0009. Safe to re-run.
-- ============================================================================

-- ------------------------------------------------------- how to reach you

-- Your phone number and Telegram handle, in the database rather than in the
-- app. You will change your Telegram handle one day and you should not need
-- an app release to do it — a merchant staring at a dead link is worse than
-- one who has to search for you.
--
-- Exactly one row, enforced by the primary key: `id` is a boolean that must be
-- true, so a second row cannot exist to disagree with the first.
create table if not exists public.platform_settings (
  id               boolean primary key default true check (id),
  support_phone    text not null default '',
  support_telegram text not null default '',
  -- Free text, shown under the buttons: "Mon–Sat, 8am–8pm".
  support_hours    text not null default '',
  updated_at       timestamptz not null default now()
);

insert into public.platform_settings (id) values (true)
  on conflict (id) do nothing;

alter table public.platform_settings enable row level security;

-- Readable by anyone, including a diner who will never see it. There is
-- nothing here that is not already printed on a business card, and the
-- alternative — an RPC — buys nothing.
drop policy if exists platform_settings_read on public.platform_settings;
create policy platform_settings_read on public.platform_settings
  for select using (true);

-- No write policy. Changed in the SQL editor, like membership of
-- platform_admins: it is your contact detail, not a merchant's.

-- --------------------------------------------------------------- the queue

create table if not exists public.upgrade_requests (
  id            uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null
                  references public.restaurants(id) on delete cascade,
  -- What they were on when they asked. Kept even after they move, so the
  -- console can say "Basic → Pro" a week later without guessing.
  from_plan     text not null check (from_plan in ('FREE','BASIC','PRO')),
  to_plan       text not null check (to_plan in ('FREE','BASIC','PRO')),
  -- What they were doing when they hit the wall. STAFF_CAP and TABLE_CAP come
  -- from the block itself; MANUAL is someone browsing the pricing screen.
  reason        text not null
                  check (reason in ('STAFF_CAP','TABLE_CAP','MANUAL')),
  -- Who to call. Defaults to the restaurant's own phone number, but a merchant
  -- may want you on their mobile rather than the shop line.
  contact_name  text not null default '',
  contact_phone text not null default '',
  note          text not null default '',
  status        text not null default 'NEW'
                  check (status in ('NEW','CONTACTED','DONE','DECLINED')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  handled_at    timestamptz,
  handled_by    uuid references auth.users(id) on delete set null,
  -- Your note to yourself, never shown to the merchant.
  handled_note  text not null default ''
);

-- One open request per merchant. A partial unique index rather than a plain
-- one: a merchant who upgraded in March and asks again in June is two rows,
-- and both are worth keeping.
create unique index if not exists upgrade_requests_one_open
  on public.upgrade_requests (restaurant_id)
  where status in ('NEW','CONTACTED');

create index if not exists upgrade_requests_queue
  on public.upgrade_requests (status, created_at);

alter table public.upgrade_requests enable row level security;

-- The merchant reads their own. Nobody writes through the table — writes go
-- through request_upgrade() below, so the restaurant_id is taken from the
-- caller's staff row and never from what the client sends.
drop policy if exists upgrade_requests_read_own on public.upgrade_requests;
create policy upgrade_requests_read_own on public.upgrade_requests
  for select using (restaurant_id = public.current_restaurant_id());

-- ------------------------------------------------------- filing a request

create or replace function public.request_upgrade(
  p_to_plan       text,
  p_reason        text,
  p_contact_name  text,
  p_contact_phone text,
  p_note          text default ''
)
returns public.upgrade_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_restaurant uuid;
  v_plan       text;
  v_row        public.upgrade_requests;
begin
  -- The owner asks. A cashier who found the pricing screen does not commit
  -- their employer to a bill.
  if not public.can_manage_restaurant() then
    raise exception 'Only the owner can ask for a plan change';
  end if;

  v_restaurant := public.current_restaurant_id();
  select plan into v_plan from public.restaurants where id = v_restaurant;

  if p_to_plan not in ('FREE','BASIC','PRO') then
    raise exception 'Unknown plan %', p_to_plan;
  end if;
  if p_reason not in ('STAFF_CAP','TABLE_CAP','MANUAL') then
    raise exception 'Unknown reason %', p_reason;
  end if;

  -- Second tap edits the first request. `updated_at` moves so the console can
  -- tell a merchant who asked once from one who has now asked three times and
  -- is getting impatient; `created_at` does not, because how long they have
  -- been waiting is the whole point of the queue.
  update public.upgrade_requests
     set to_plan       = p_to_plan,
         reason        = p_reason,
         contact_name  = coalesce(nullif(trim(p_contact_name), ''), contact_name),
         contact_phone = coalesce(nullif(trim(p_contact_phone), ''), contact_phone),
         note          = p_note,
         updated_at    = now()
   where restaurant_id = v_restaurant
     and status in ('NEW','CONTACTED')
   returning * into v_row;

  if found then
    return v_row;
  end if;

  insert into public.upgrade_requests (
    restaurant_id, from_plan, to_plan, reason,
    contact_name, contact_phone, note
  ) values (
    v_restaurant, v_plan, p_to_plan, p_reason,
    trim(p_contact_name), trim(p_contact_phone), p_note
  )
  returning * into v_row;

  return v_row;
end $$;

grant execute on function
  public.request_upgrade(text, text, text, text, text) to authenticated;

-- The merchant's own open request, or nothing. Separate from the select
-- policy because the app asks for exactly this and should not have to know
-- which statuses count as open.
create or replace function public.my_upgrade_request()
returns public.upgrade_requests
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select * from public.upgrade_requests
   where restaurant_id = public.current_restaurant_id()
     and status in ('NEW','CONTACTED')
   order by created_at desc
   limit 1
$$;

grant execute on function public.my_upgrade_request() to authenticated;

-- Withdrawing. A merchant who asked by mistake, or who has since spoken to
-- you, should be able to clear it themselves rather than living with a card
-- on their pricing screen that they cannot dismiss.
create or replace function public.cancel_upgrade_request()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can_manage_restaurant() then
    raise exception 'Only the owner can withdraw a plan change request';
  end if;

  update public.upgrade_requests
     set status     = 'DECLINED',
         handled_at = now(),
         updated_at = now()
   where restaurant_id = public.current_restaurant_id()
     and status in ('NEW','CONTACTED');
end $$;

grant execute on function public.cancel_upgrade_request() to authenticated;

-- ------------------------------------------------------- the operator's end

create or replace function public.platform_upgrade_requests()
returns table (
  id            uuid,
  restaurant_id uuid,
  merchant      text,
  slug          text,
  logo          text,
  merchant_phone text,
  from_plan     text,
  to_plan       text,
  reason        text,
  contact_name  text,
  contact_phone text,
  note          text,
  status        text,
  created_at    timestamptz,
  updated_at    timestamptz,
  handled_at    timestamptz
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  -- Open ones first and oldest first within that: the queue is ordered by how
  -- long somebody has been waiting, not by how much they would pay.
  select r.id, r.restaurant_id, m.name, m.slug, m.logo, m.phone,
         r.from_plan, r.to_plan, r.reason,
         r.contact_name, r.contact_phone, r.note,
         r.status, r.created_at, r.updated_at, r.handled_at
    from public.upgrade_requests r
    join public.restaurants m on m.id = r.restaurant_id
   where public.is_platform_admin()
     -- Resolved requests stay visible for a fortnight. Long enough to see what
     -- you did last week, short enough that the queue is still a queue.
     and (r.status in ('NEW','CONTACTED')
          or r.handled_at > now() - interval '14 days')
   order by (r.status in ('NEW','CONTACTED')) desc, r.created_at
$$;

grant execute on function public.platform_upgrade_requests() to authenticated;

create or replace function public.platform_resolve_upgrade_request(
  p_id     uuid,
  p_status text,
  p_note   text default ''
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_platform_admin() then
    raise exception 'Not a platform administrator';
  end if;
  if p_status not in ('NEW','CONTACTED','DONE','DECLINED') then
    raise exception 'Unknown status %', p_status;
  end if;

  update public.upgrade_requests
     set status       = p_status,
         handled_note = p_note,
         updated_at   = now(),
         -- Moving one back to CONTACTED reopens it, so the handled stamp has
         -- to come off as well or it would show as dealt with in the queue.
         handled_at   = case when p_status in ('DONE','DECLINED')
                             then now() else null end,
         handled_by   = auth.uid()
   where id = p_id;

  if not found then
    raise exception 'Unknown request';
  end if;
end $$;

grant execute on function
  public.platform_resolve_upgrade_request(uuid, text, text) to authenticated;

-- --------------------------------------------- changing the plan closes it

-- The operator's most likely path is to skip the queue entirely: read the
-- request, agree, change the plan. Without this the request they just granted
-- sits in the queue looking outstanding, and the merchant's app keeps saying
-- "we have your request" after they are already on Pro.
create or replace function public.close_upgrade_request_on_plan_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.plan is distinct from old.plan then
    update public.upgrade_requests
       set status     = 'DONE',
           handled_at = now(),
           updated_at = now()
     where restaurant_id = new.id
       and status in ('NEW','CONTACTED');
  end if;
  return new;
end $$;

drop trigger if exists restaurants_close_upgrade_request on public.restaurants;
create trigger restaurants_close_upgrade_request
  after update of plan on public.restaurants
  for each row execute function public.close_upgrade_request_on_plan_change();

-- ============================================================================
--  Set your contact details:
--
--    update public.platform_settings set
--      support_phone    = '+855 12 345 678',
--      support_telegram = 'https://t.me/yourhandle',
--      support_hours    = 'Mon–Sat, 8am–8pm',
--      updated_at       = now();
-- ============================================================================
